### ISSUE TITLE
Server some time crash and Shutdown

### ISSUE THREAD

**Issue by caizhong3** [Xephi/AuthMeReloaded#1002]
When I use Authme Reloaded version
The server often shuntdown and crash

But using the old version is normal (AuthMe3.4)

### Plugin list:
**ColoredSigns, MonsterPower, GroupManager, WrenchLog, AntiAdvSPGuiBug, FarmProtect, AsyncKeepAlive, exp_repair, Bestmessage, DeathMessages, BanItem, RemoteController, Yum, RideMe, LWCField, AntiCraft, RichAutoMessage, CoreProtect, WorldEdit, WorldManager, Essentials, Restart, Frame_Protector, WorldBorder, ProtocolLib, EssentialsChat, PTweaks, TreeAssist, FunnyFoot, UltimateGuild, commandeny, ResidenceAssist, Mcrmb, Vault, WrenchLimit, MultiServerChat_Client, NeverLag, LWC, QuickShop, McrmbShop, LuckyRedPackets, Marriage, ChestCommands, EssentialsProtect, EssentialsAntiBuild, McrmbVip, RandomLocation, ScratchCards, EssentialsSpawn, PlotMe, MCLib, ColorMOTD, Multiverse-Core, Residence, AuthMe, HolographicDisplays**

### Environment description
Server version:KCauldron:1.7.10-1614.201
Authme using MySql

### AuthMe build number:
build number 5.2-SNAPSHOT-b1448(Earlier versions are also tested) 

### Error Log:
(useful log)
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 16-10-30 上午11:00
Description: Ticking entity

java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
	at java.util.LinkedList$ListItr.next(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:344)
	at net.minecraft.world.World.func_72866_a(World.java:2674)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:800)
	at net.minecraft.world.World.func_72870_g(World.java:2623)
	at net.minecraft.world.World.func_72939_s(World.java:2423)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
	at java.util.LinkedList$ListItr.next(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:344)
	at net.minecraft.world.World.func_72866_a(World.java:2674)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:800)
	at net.minecraft.world.World.func_72870_g(World.java:2623)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 270682
	Entity Name: SnowHalation
	Entity's Exact location: -706.00, 73.00, -264.00
	Entity's Block location: World: (-706,73,-264), Chunk: (at 14,4,8 in -45,-17; contains blocks -720,0,-272 to -705,255,-257), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2423)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)

### Configuration:
just change MySql setting

**Comment by caizhong3** [comment]
When using AuthmeReloaded has the same error
Ticking PlayerEntity

**Comment by sgdc3** [comment]
> When using AuthmeReloaded all version has the same error
All authme or server version?

**Comment by ljacqu** [comment]
Closing, no answer.
