### ISSUE TITLE
AuthMe error (Spigot 1.11)

### ISSUE THREAD

**Issue by RikoDEV** [Xephi/AuthMeReloaded#1008]
Hi, I have a error on latest 1.11 spigot and latest AuthMe DevBuild.
```
[07:17:14] [Server thread/WARN]: [AuthMe] Task #43 for AuthMe v5.2-SNAPSHOT-b1465 generated an exception
java.lang.NullPointerException
	at fr.xephi.authme.task.purge.PurgeTask.run(PurgeTask.java:75) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[paperclip.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [paperclip.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [paperclip.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [paperclip.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [paperclip.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [paperclip.jar:git-Spigot-16c940b-0805f60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by sgdc3** [comment]
Happened once or more times? @RikoDEV

**Comment by RikoDEV** [comment]
@sgdc3 error is repeated in a loop and spam console

**Comment by sgdc3** [comment]
strange, it should happen only when the server fails to convert an uuid to name, does it happen in 1.10?

**Comment by RikoDEV** [comment]
@sgdc3 no, on spigot 1.10 works fine

**Comment by ljacqu** [comment]
Apparently, `OfflinePlayer#getName` may return `null`. I can understand how this makes sense since Minecraft switched to using UUIDs as primary identifier, but I'm still a little stumped at the fact that this does not happen in 1.10 but that it does in 1.11. 

@RikoDEV If we provide to you a JAR with some debug output, could we ask you to perform a purge on 1.10 vs. one in 1.11? The log output would certainly be interesting, but I understand if it's too much of a hassle.

**Comment by RikoDEV** [comment]
@ljacqu yes

**Comment by ljacqu** [comment]
@RikoDEV Cool, thanks! If you could use the JAR from https://github.com/ljacqu/AuthMeReloaded/tree/1008-debug-npe-on-purge/samples and enable logging to authme.log, it will log each player it processes in the log. Then we could compare between 1.10 and 1.11.

https://github.com/ljacqu/AuthMeReloaded/tree/1008-debug-npe-on-purge/samples

You can enable logging in your config.yml:
```yml
        # Copy AuthMe log output in a separate file as well?
        logConsole: true
```

**Comment by ljacqu** [comment]
Hang on a minute,  if you use the other jar again it will cause an error? As long as "No players to purge" is logged we won't go through the purge process

**Comment by RikoDEV** [comment]
Strange, I used the old .jar where I received an error and no longer displays.

**Comment by ljacqu** [comment]
> [INFO] No players to purge

As long as it doesn't have any player to purge, it won't run the purge task. But the error is inside the purge task.

**Comment by RikoDEV** [comment]
Wait, I run the plugin witch purge. And i see a error...

**Comment by RikoDEV** [comment]
authme.log:
```
[11-19 14:56:53]: [INFO] SQLite driver loaded
[11-19 14:56:54]: [INFO] SQLite Setup finished
[11-19 14:56:54]: [INFO] Hooked into Vault!
[11-19 14:56:54]: [INFO] Hooked successfully into Essentials
[11-19 14:56:54]: [INFO] [LICENSE] This product uses data from the GeoLite API created by MaxMind, available at http://www.maxmind.com
[11-19 14:56:54]: [INFO] Development builds are available on our jenkins, thanks to f14stelt.
[11-19 14:56:54]: [INFO] Do you want a good game server? Look at our sponsor GameHosting.it leader in Italy as Game Server Provider!
[11-19 14:56:54]: [INFO] AuthMe 5.2-SNAPSHOT build n.1464 correctly enabled!
[11-19 14:56:54]: [INFO] Automatically purging the database...
[11-19 14:57:18]: [INFO] AuthMe 5.2-SNAPSHOT-b1464 disabled!
```

**Comment by ljacqu** [comment]
Could you post the log with the error please? This one doesn't have any error.

**Comment by RikoDEV** [comment]
I don't have a error in authme.log only on server logs

**Comment by ljacqu** [comment]
OK, is it possible to post that one then? Is it again like in the first post?

**Comment by ljacqu** [comment]
What I'm trying here is to get you to run the JAR from https://github.com/Xephi/AuthMeReloaded/issues/1008#issuecomment-261714358 and to execute the purge task (and that it really purges). Where we would expect an error with the regular JAR we will hopefully gather some interesting info with the special JAR.

**Comment by RikoDEV** [comment]
Yes, it is like first post.

**Comment by RikoDEV** [comment]
@ljacqu in this build purge works fine

**Comment by ljacqu** [comment]
Please,
- use the JAR linked in https://github.com/Xephi/AuthMeReloaded/issues/1008#issuecomment-261714358
- run the purge task (it must purge users; in https://github.com/Xephi/AuthMeReloaded/issues/1008#issuecomment-261714849 it just says "no players to purge")
- post the authme.log from 1.10 and 1.11

**Comment by RikoDEV** [comment]
1.10....
```
[11-19 15:53:45]: [INFO] SQLite driver loaded
[11-19 15:53:45]: [INFO] SQLite Setup finished
[11-19 15:53:45]: [INFO] No supported permissions system found! Permissions are disabled!
[11-19 15:53:46]: [INFO] [LICENSE] This product uses data from the GeoLite API created by MaxMind, available at http://www.maxmind.com
[11-19 15:53:46]: [WARN] WARNING! The protectInventory feature requires ProtocolLib! Disabling it...
[11-19 15:53:46]: [WARN] WARNING! The denyTabComplete feature requires ProtocolLib! Disabling it...
[11-19 15:53:46]: [INFO] Development builds are available on our jenkins, thanks to f14stelt.
[11-19 15:53:46]: [INFO] Do you want a good game server? Look at our sponsor GameHosting.it leader in Italy as Game Server Provider!
[11-19 15:53:46]: [INFO] AuthMe 5.2-SNAPSHOT build n.CUSTOM correctly enabled!
[11-19 15:53:46]: [INFO] Automatically purging the database...
[11-19 15:53:46]: [INFO] PURGE: Processing OfflinePlayer[uuid='eb17b0d4-038c-4749-9a23-d5d3df35fb59', name='PolskiRiko2']
[11-19 15:53:46]: [INFO] PURGE: Processing OfflinePlayer[uuid='8c831176-7de0-3b53-b2b7-22d84af5fd99', name='null']
[11-19 15:53:46]: [INFO] Finished lookup of offlinePlayers. Begin looking purging player names only
[11-19 15:53:46]: [INFO] §6Deleted 1 user accounts
[11-19 15:53:46]: [INFO] AutoPurge: Removed 0 .dat Files
[11-19 15:53:46]: [INFO] Purge finished!
```

1.11:
```
[11-19 15:54:51]: [INFO] SQLite driver loaded
[11-19 15:54:52]: [INFO] SQLite Setup finished
[11-19 15:54:52]: [INFO] No supported permissions system found! Permissions are disabled!
[11-19 15:54:52]: [INFO] [LICENSE] This product uses data from the GeoLite API created by MaxMind, available at http://www.maxmind.com
[11-19 15:54:52]: [WARN] WARNING! The protectInventory feature requires ProtocolLib! Disabling it...
[11-19 15:54:52]: [WARN] WARNING! The denyTabComplete feature requires ProtocolLib! Disabling it...
[11-19 15:54:52]: [INFO] Development builds are available on our jenkins, thanks to f14stelt.
[11-19 15:54:52]: [INFO] Do you want a good game server? Look at our sponsor GameHosting.it leader in Italy as Game Server Provider!
[11-19 15:54:52]: [INFO] AuthMe 5.2-SNAPSHOT build n.CUSTOM correctly enabled!
[11-19 15:54:52]: [INFO] Automatically purging the database...
[11-19 15:54:52]: [INFO] PURGE: Processing OfflinePlayer[uuid='eb17b0d4-038c-4749-9a23-d5d3df35fb59', name='PolskiRiko2']
[11-19 15:54:52]: [INFO] PURGE: Processing OfflinePlayer[uuid='8c831176-7de0-3b53-b2b7-22d84af5fd99', name='null']
[11-19 15:54:52]: [INFO] §6Deleted 1 user accounts
[11-19 15:54:52]: [INFO] AutoPurge: Removed 0 .dat Files
[11-19 15:54:52]: [INFO] Finished lookup of offlinePlayers. Begin looking purging player names only
[11-19 15:54:52]: [INFO] §6Deleted 2 user accounts
[11-19 15:54:52]: [INFO] AutoPurge: Removed 0 .dat Files
[11-19 15:54:53]: [INFO] Purge finished!
```

**Comment by ljacqu** [comment]
Thanks, I need to play this through with the code and I'll deliver you my results later on. What I can see at first glance, `name='null'` is in both logs, so looks like it's not related to Minecraft 1.11. It's surprising that you're the first one to report this error, but we will fix it. :) It's a quick fix in the code but it's important for us to understand _why_ this is happening so we don't break the purge process.

Is there anything special with the player with UUID 8c831176-7de0-3b53-b2b7-22d84af5fd99 that you would know about?

**Comment by RikoDEV** [comment]
8c831176-7de0-3b53-b2b7-22d84af5fd99 is my non-premium old account UUID. Authme save new UUID for premium account and name this "null"

**Comment by ljacqu** [comment]
Thanks for the info, that makes sense! In online mode we can expect that the server will not be able to map your offline UUID to any map. I've added the same fix to the normal build as in the special JAR, so I close this. Thanks a lot for your time and for all the information you could provide to shed light on this issue. :)
