### ISSUE TITLE
Problem with spigot 1.10

### ISSUE THREAD

**Issue by Daewo147** [Xephi/AuthMeReloaded#1011]
Hi. I from Poland and my english its no perfect. I have VPS i install and run spigot for minecraft 1.10. I download and start plugin AuthMe and have problem. My logs:

`[23:47:20] [Server thread/ERROR]: Could not load 'plugins/AuthMe-5.2-SNAPSHOT-spigot.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: fr/xephi/authme/AuthMe : Unsupported major.minor version 52.0
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-Spigot-de459a2-51263e9]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-de459a2-51263e9]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-de459a2-51263e9]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot.jar:git-Spigot-de459a2-51263e9]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot.jar:git-Spigot-de459a2-51263e9]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot.jar:git-Spigot-de459a2-51263e9]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_111]
Caused by: java.lang.UnsupportedClassVersionError: fr/xephi/authme/AuthMe : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_111]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:803) ~[?:1.7.0_111]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_111]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_111]
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_111]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_111]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_111]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_111]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_111]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-de459a2-51263e9]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-de459a2-51263e9]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_111]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_111]
    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_111]
    at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_111]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-de459a2-51263e9]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-de459a2-51263e9]
    ... 6 more
 `

**Comment by ljacqu** [comment]
> Unsupported major.minor version 52.0

Your server is running Java 7. AuthMe switched to Java 8 a few months ago.
