### ISSUE TITLE
Vault NPE

### ISSUE THREAD

**Issue by lucko** [Xephi/AuthMeReloaded#1018]
One of my users reported this error:
```
[18:46:41 WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.2-SNAPSHOT-b1476 generated an exception while executing task 202
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: groupName
        at me.lucko.luckperms.bukkit.vault.VaultPermissionHook.playerRemoveGroup(VaultPermissionHook.java:273)
        at net.milkbowl.vault.permission.Permission.playerRemoveGroup(Permission.java:641)
        at net.milkbowl.vault.permission.Permission.playerRemoveGroup(Permission.java:654)
        at fr.xephi.authme.permission.handlers.VaultHandler.removeFromGroup(VaultHandler.java:59)
        at fr.xephi.authme.permission.PermissionsManager.removeGroup(PermissionsManager.java:360)
        at fr.xephi.authme.permission.PermissionsManager.removeGroups(PermissionsManager.java:380)
        at fr.xephi.authme.permission.AuthGroupHandler.setGroup(AuthGroupHandler.java:71)
        at fr.xephi.authme.process.ProcessService.setGroup(ProcessService.java:111)
        at fr.xephi.authme.process.join.AsynchronousJoin.processJoin(AsynchronousJoin.java:111)
        at fr.xephi.authme.process.Management.lambda$performJoin$6(Management.java:75)
        at fr.xephi.authme.process.Management$$Lambda$178/1998039880.run(Unknown Source)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

It seems that this is null:
https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/permission/AuthGroupHandler.java#L30

which is eventually throwing an NPE when called here:
https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/permission/AuthGroupHandler.java#L71

Here's his config: http://hastebin.com/akecalipun.bash

I'm not too sure how that #reload method functions. I guess it's not being called, or the property is just returning null?

Sorry for the somewhat vague info, but that's all I got. :)

### AuthMe build number:
1476 (the latest)

**Comment by ljacqu** [comment]
Thanks for the detailed report, what an embarrassing bug :P I think this should be fixed with build n. 1477 or above at http://ci.xephi.fr/job/AuthMeReloaded/. If I could ask you for some quick feedback, that would be lovely :)

**Comment by Eufranio** [comment]
It's fixed, thanks @ljacq

**Comment by ljacqu** [comment]
Thanks (my username ends with a U btw)
