### ISSUE TITLE
Plugin broken with latest spigot build

### ISSUE THREAD

**Issue by bykidi** [Xephi/AuthMeReloaded#102]
So i just redownload buildtools, recompile latest spigot 1.8.7, started latest plugin and its crash

```
[16:02:55] [Server thread/ERROR]: Could not load 'plugins/AuthMe.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: fr/xephi/authme/AuthMe : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.UnsupportedClassVersionError: fr/xephi/authme/AuthMe : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_75]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_75]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_75]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_75]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_75]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_75]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_75]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_75]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_75]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_75]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_75]
	at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_75]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	... 6 more
```

**Comment by sgdc3** [comment]
You must compile it with jdk 7!

**Comment by sgdc3** [comment]
If you compile with jdk 8 you must execute the jar file under java 8 too!

**Comment by sgdc3** [comment]
If you compile it with jdk 7 it will also work on java 8 ;)

**Comment by bykidi** [comment]
I don't compile AuthMe its self :)
I compile only buildtools (with latest windows java8 update 45) and download authme directly from spigot download page

[16:02:54] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-f928e7a-e91aed8 (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)

**Comment by sgdc3** [comment]
Sorry, i misread the issue xD
It's a java version issue anyway...

**Comment by sgdc3** [comment]
If you know how to compile a maven project try to build AuthMe with the same jdk version of BuildTools

**Comment by bykidi** [comment]
I just asked my hoster provider to update server version of Java (was 1.7.0_75, now 1.8.0_45) and problem fixed now!
Thank you!

[16:51:45] [Server thread/INFO]: [AuthMe] Loading AuthMe v5.0-SNAPSHOT
[16:51:50] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.0-SNAPSHOT
[16:51:50] [Server thread/INFO]: [AuthMe] Loading Configuration File...
[16:51:50] [Server thread/INFO]: [AuthMe] Set Language: ru
[16:51:50] [Server thread/INFO]: [AuthMe] Vault plugin detected, hook with PermissionsEx system
[16:51:50] [Server thread/INFO]: [AuthMe] Hook with Essentials plugin
[16:51:50] [Server thread/INFO]: [AuthMe] Hook with EssentialsSpawn plugin
[16:51:50] [Server thread/INFO]: [AuthMe] [LICENSE] This product includes GeoLite data created by MaxMind, available from http://www.maxmind.com
[16:51:50] [Server thread/INFO]: [AuthMe] [SPONSOR] AuthMe is sponsored and hook perfectly with server hosting VERYGAMES, rent your server for only 1.99$/months
[16:51:50] [Server thread/INFO]: [AuthMe] [SPONSOR] Look Minecraft and other offers on www.verygames.net ! 
[16:51:50] [Server thread/INFO]: [AuthMe] Authme 5.0-SNAPSHOT enabled

**Comment by sgdc3** [comment]
You're welcome! ;)

**Comment by sgdc3** [comment]
Close the issue please
