### ISSUE TITLE
I got a problem

### ISSUE THREAD

**Issue by SourcePowered** [Xephi/AuthMeReloaded#1028]
Server version: Spigot 1.10.2 latest version.
Plugin version: Latest version on jenkins

The server is always automatically shut down, I don't know why, so I make stopServer: false.
And then:

```
[21:05:09 WARN]: [AuthMe] Plugin AuthMe v5.2-SNAPSHOT-b1384 generated an exception while executing task 48
java.lang.NullPointerException
        at org.sqlite.PrepStmt.<init>(PrepStmt.java:42) ~[PaperSpigot_Server.jar:git-Paper-916.2]
        at org.sqlite.Conn.prepareStatement(Conn.java:404) ~[PaperSpigot_Server.jar:git-Paper-916.2]
        at org.sqlite.Conn.prepareStatement(Conn.java:399) ~[PaperSpigot_Server.jar:git-Paper-916.2]
        at org.sqlite.Conn.prepareStatement(Conn.java:383) ~[PaperSpigot_Server.jar:git-Paper-916.2]
        at fr.xephi.authme.datasource.SQLite.getAccountsRegistered(SQLite.java:538) ~[?:?]
        at fr.xephi.authme.datasource.CacheDataSource.getAccountsRegistered(CacheDataSource.java:220) ~[?:?]
        at fr.xephi.authme.initialization.Initializer$1.run(Initializer.java:119) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[PaperSpigot_Server.jar:git-Paper-916.2]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [PaperSpigot_Server.jar:git-Paper-916.2]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [PaperSpigot_Server.jar:git-Paper-916.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_102]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
```

**Comment by SourcePowered** [comment]
What... If I delete PermissionsEx, every thing is OK.
But.............My PermissionsEx version is 2.0...Not 1.X...

**Comment by sgdc3** [comment]
PermissionEx is not yet available for Bukkit :/

**Comment by SourcePowered** [comment]
@sgdc3 You mean PEX 2.0 is not available?...

**Comment by sgdc3** [comment]
https://dev.bukkit.org/projects/permissionsex/files
