### ISSUE TITLE
Failed to send a mail

### ISSUE THREAD

**Issue by techxiu** [Xephi/AuthMeReloaded#1072]
org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1421)
	at org.apache.commons.mail.Email.send(Email.java:1448)
	at fr.xephi.authme.mail.SendMailSSL.sendEmail(SendMailSSL.java:171)
	at fr.xephi.authme.mail.SendMailSSL.sendRecoveryCode(SendMailSSL.java:109)
	at fr.xephi.authme.command.executable.email.RecoverEmailCommand.createAndSendRecoveryCode(RecoverEmailCommand.java:87)
	at fr.xephi.authme.command.executable.email.RecoverEmailCommand.runCommand(RecoverEmailCommand.java:75)
	at fr.xephi.authme.command.PlayerCommand.executeCommand(PlayerCommand.java:16)
	at fr.xephi.authme.command.CommandHandler.executeCommand(CommandHandler.java:116)
	at fr.xephi.authme.command.CommandHandler.handleCommandResult(CommandHandler.java:75)
	at fr.xephi.authme.command.CommandHandler.processCommand(CommandHandler.java:68)
	at fr.xephi.authme.AuthMe.onCommand(AuthMe.java:385)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1999)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:709)
	at javax.mail.Service.connect(Service.java:386)
	at javax.mail.Service.connect(Service.java:245)
	at javax.mail.Service.connect(Service.java:194)
	at javax.mail.Transport.send0(Transport.java:253)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1411)
	... 26 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:543)
	at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:480)
	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1994)
	... 33 more

**Comment by sgdc3** [comment]
Have you enabled "less secure applications" in gmail settings? https://support.google.com/accounts/answer/6010255?hl=en

**Comment by friishon** [comment]
When enable "less secure applications" and then try to send the email, works,
Send the email whith the code to recover the password

**Comment by friishon** [comment]
With*
