### ISSUE TITLE
Bungeecord crashing D:

### ISSUE THREAD

**Issue by aBo0oDGamer** [Xephi/AuthMeReloaded#1099]
Hello ,
i'm running a bungeecord network and i want to make players register in the lobby server but when i put the plugin in the plugins folder of lobby the server turning on and off on and off without stop why D:
i see file in the plugin folder (authme.log) and this is what in it:
`[02-17 20:30:27]: [INFO] SQLite driver loaded
[02-17 20:30:27]: [INFO] SQLite Setup finished
[02-17 20:30:27]: [INFO] Hooked into Essentials Group Manager!
[02-17 20:30:27]: [INFO] Hooked successfully into Essentials
[02-17 20:30:27]: [INFO] Hooked successfully into Multiverse-Core
[02-17 20:30:27]: [WARN] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[02-17 20:30:27]: ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
	at ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
	at ch.jalu.injector.handlers.instantiation.ConstructorInjection.instantiateWith(ConstructorInjection.java:39)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:184)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:51)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:240)
	at fr.xephi.authme.AuthMe.initializeServices(AuthMe.java:202)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:128)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: Lcom/google/gson/Gson;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at ch.jalu.injector.utils.ReflectionUtils.safeGetDeclaredFields(ReflectionUtils.java:177)
	at ch.jalu.injector.handlers.instantiation.ConstructorInjectionProvider.validateHasNoOtherInjectAnnotations(ConstructorInjectionProvider.java:45)
	at ch.jalu.injector.handlers.instantiation.ConstructorInjectionProvider.safeGet(ConstructorInjectionProvider.java:21)
	at ch.jalu.injector.handlers.instantiation.ConstructorInjectionProvider.safeGet(ConstructorInjectionProvider.java:13)
	at ch.jalu.injector.handlers.instantiation.DirectInstantiationProvider.get(DirectInstantiationProvider.java:16)
	at ch.jalu.injector.InjectorImpl.getInstantiation(InjectorImpl.java:190)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:180)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at ch.jalu.injector.InjectorImpl.newInstance(InjectorImpl.java:78)
	at fr.xephi.authme.command.CommandHandler.initializeCommands(CommandHandler.java:99)
	at fr.xephi.authme.command.CommandHandler.<init>(CommandHandler.java:45)
	... 23 more
Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more

[02-17 20:30:27]: [WARN] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[02-17 20:30:27]: [INFO] AuthMe 5.2-SNAPSHOT-b1292 disabled!
[02-17 20:30:41]: [INFO] SQLite driver loaded
[02-17 20:30:41]: [INFO] SQLite Setup finished
[02-17 20:30:41]: [INFO] Hooked into Essentials Group Manager!
[02-17 20:30:41]: [INFO] Hooked successfully into Essentials
[02-17 20:30:41]: [INFO] Hooked successfully into Multiverse-Core
[02-17 20:30:41]: [INFO] [LICENSE] This product uses data from the GeoLite API created by MaxMind, available at http://www.maxmind.com
[02-17 20:30:41]: [WARN] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[02-17 20:30:41]: ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
	at ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
	at ch.jalu.injector.handlers.instantiation.ConstructorInjection.instantiateWith(ConstructorInjection.java:39)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:184)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:51)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:240)
	at fr.xephi.authme.AuthMe.initializeServices(AuthMe.java:202)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:128)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: Lcom/google/gson/Gson;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at ch.jalu.injector.utils.ReflectionUtils.safeGetDeclaredFields(ReflectionUtils.java:177)
	at ch.jalu.injector.handlers.instantiation.ConstructorInjectionProvider.validateHasNoOtherInjectAnnotations(ConstructorInjectionProvider.java:45)
	at ch.jalu.injector.handlers.instantiation.ConstructorInjectionProvider.safeGet(ConstructorInjectionProvider.java:21)
	at ch.jalu.injector.handlers.instantiation.ConstructorInjectionProvider.safeGet(ConstructorInjectionProvider.java:13)
	at ch.jalu.injector.handlers.instantiation.DirectInstantiationProvider.get(DirectInstantiationProvider.java:16)
	at ch.jalu.injector.InjectorImpl.getInstantiation(InjectorImpl.java:190)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:180)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at ch.jalu.injector.InjectorImpl.newInstance(InjectorImpl.java:78)
	at fr.xephi.authme.command.CommandHandler.initializeCommands(CommandHandler.java:99)
	at fr.xephi.authme.command.CommandHandler.<init>(CommandHandler.java:45)
	... 23 more
Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 54 more

[02-17 20:30:41]: [WARN] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[02-17 20:30:41]: [INFO] AuthMe 5.2-SNAPSHOT-b1292 disabled!
[02-17 20:30:53]: [INFO] SQLite driver loaded
[02-17 20:30:53]: [INFO] SQLite Setup finished
[02-17 20:30:53]: [INFO] Hooked into Essentials Group Manager!
[02-17 20:30:53]: [INFO] [LICENSE] This product uses data from the GeoLite API created by MaxMind, available at http://www.maxmind.com
[02-17 20:30:53]: [INFO] Hooked successfully into Essentials
[02-17 20:30:53]: [INFO] Hooked successfully into Multiverse-Core
[02-17 20:30:53]: [WARN] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[02-17 20:30:53]: ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
	at ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
	at ch.jalu.injector.handlers.instantiation.ConstructorInjection.instantiateWith(ConstructorInjection.java:39)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:184)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:51)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:240)
	at fr.xephi.authme.AuthMe.initializeServices(AuthMe.java:202)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:128)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: Lcom/google/gson/Gson;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at ch.jalu.injector.utils.ReflectionUtils.safeGetDeclaredFields(ReflectionUtils.java:177)
	at ch.jalu.injector.handlers.instantiation.ConstructorInjectionProvider.validateHasNoOtherInjectAnnotations(ConstructorInjectionProvider.java:45)
	at ch.jalu.injector.handlers.instantiation.ConstructorInjectionProvider.safeGet(ConstructorInjectionProvider.java:21)
	at ch.jalu.injector.handlers.instantiation.ConstructorInjectionProvider.safeGet(ConstructorInjectionProvider.java:13)
	at ch.jalu.injector.handlers.instantiation.DirectInstantiationProvider.get(DirectInstantiationProvider.java:16)
	at ch.jalu.injector.InjectorImpl.getInstantiation(InjectorImpl.java:190)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:180)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at ch.jalu.injector.InjectorImpl.newInstance(InjectorImpl.java:78)
	at fr.xephi.authme.command.CommandHandler.initializeCommands(CommandHandler.java:99)
	at fr.xephi.authme.command.CommandHandler.<init>(CommandHandler.java:45)
	... 23 more
Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 54 more

[02-17 20:30:53]: [WARN] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[02-17 20:30:53]: [INFO] AuthMe 5.2-SNAPSHOT-b1292 disabled!
`
i'm using AuthMe-5.2-SNAPSHOT-spigot i tried to use authme 5.2 the last version but the same problem 
the problem form authme 100% when i remove the plugin the server work fine and when i put it the server back to the problem why? and how can i fix it
Help Please D:

**Comment by Twonox** [comment]
You don't use a recent version of authme.
Please use this version: https://www.spigotmc.org/resources/authme-reloaded.6269/update?update=141346
And say us if the problem persist.

**Comment by aBo0oDGamer** [comment]
i already use it and the problem still and i use it now and the same problem D:

**Comment by sgdc3** [comment]
Are you using Java 8?

**Comment by aBo0oDGamer** [comment]
i'm in host i don't know i will ask him

**Comment by ljacqu** [comment]
> Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson

I think you need to use the legacy jar, from http://ci.xephi.fr/job/AuthMeReloaded/ (choose the latest blue number and download the -legacy.jar)

What server are you running on?

**Comment by Twonox** [comment]
"net.minecraft.server.v1_8_R1"
It's outdated ><

**Comment by sgdc3** [comment]
> Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson

lol, I missed that

**Comment by aBo0oDGamer** [comment]
Thankssss very very very very very very much @ljacqu  its work fine now but there is a new file created when i run the server (bStats) what is that?
and thanks you all not just @ljacqu  :D

**Comment by sgdc3** [comment]
@aBo0oDGamer Since Mcstats (Metrics) is offline we moved to bStats.
