### ISSUE TITLE
NPE while getting primary permission group

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#1101]
Posted by someone on https://www.spigotmc.org/threads/authme-reloaded.62079/page-32

```
[20:09:48 WARN]: [AuthMe] Plugin AuthMe v5.2-b1542 generated an exception while executing task 218 java.lang.NullPointerException    
at net.milkbowl.vault.permission.plugins.Permission_GroupManager.getPrimaryGroup(Permission_GroupManager.java:327) ~[?:?]    
at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]    
at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]    
at fr.xephi.authme.permission.handlers.VaultHandler.getPrimaryGroup(VaultHandler.java:78) ~[?:?]    
at fr.xephi.authme.permission.PermissionsManager.getPrimaryGroup(PermissionsManager.java:280) ~[?:?]    
at fr.xephi.authme.data.limbo.LimboCache.addPlayerData(LimboCache.java:53) ~[?:?]    
at fr.xephi.authme.process.join.AsynchronousJoin.processJoin(AsynchronousJoin.java:114) ~[?:?]    
at fr.xephi.authme.process.Management.lambda$performJoin$6(Management.java:76) ~[?:?]    
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-b4417b8-3c48711]    
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-b4417b8-3c48711]    
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]    
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]    
at java.lang.Thread.run(Unknown Source) [?:1.8.0_121] 
[20:09:48 WARN]: [Essentials] Plugin Essentials v2.0.1-b467 generated an exception while executing task 226 java.lang.NullPointerException    
at net.milkbowl.vault.permission.plugins.Permission_GroupManager.getPrimaryGroup(Permission_GroupManager.java:327) ~[?:?]    
at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]    
at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]    
at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getGroup(AbstractVaultHandler.java:33) ~[?:?]    
at com.earth2me.essentials.perm.PermissionsHandler.getGroup(PermissionsHandler.java:28) ~[?:?]    
at com.earth2me.essentials.User.getGroup(User.java:622) ~[?:?]    
at com.earth2me.essentials.textreader.TextInput.<init>(TextInput.java:28) ~[?:?]    
at com.earth2me.essentials.EssentialsPlayerListener.delayedJoin(EssentialsPlayerListener.java:209) ~[?:?]    
at com.earth2me.essentials.EssentialsPlayerListener$1.run(EssentialsPlayerListener.java:179) ~[?:?]    
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-b4417b8-3c48711]    
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-b4417b8-3c48711]    
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]    
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]    
at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
```

**Comment by ljacqu** [comment]
Voting to close this as this isn't our fault—there's a stacktrace from Essentials right under ours, i.e. Vault should fix this. Since the person who submitted this stacktrace never provided more details, closing.
