### ISSUE TITLE
Exception in thread "Craft Scheduler Thread - 38" 

### ISSUE THREAD

**Issue by prozhong** [Xephi/AuthMeReloaded#123]
[20:10:21] [Craft Scheduler Thread - 38/WARN]: Exception in thread "Craft Scheduler Thread - 38" 
[20:10:21] [Craft Scheduler Thread - 38/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing task 121477
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@52a52e0a rejected from java.util.concurrent.ThreadPoolExecutor@134aa862[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Unknown Source)
	at fr.xephi.authme.datasource.DatabaseCalls.isAuthAvailable(DatabaseCalls.java:23)
	at fr.xephi.authme.AuthMe.getAuthMeSpawn(AuthMe.java:583)
	at fr.xephi.authme.AuthMe.getSpawnLocation(AuthMe.java:552)
	at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:94)
	at fr.xephi.authme.process.Management$5.run(Management.java:81)
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

#_54 DEV

http://pastebin.com/A8cjEhcz

**Comment by ReFruity** [comment]
```
[22:31:35 INFO]: UUID of player sas is a3d60693-b434-3568-9b74-b268ef3772cd                                                        
[22:31:35 INFO]: sas[/88.200.215.105:40864] logged in with entity id 9685 at ([world]158.13577352653468, 93.0, 139.19728961397914) 
[22:31:35 WARN]: Exception in thread "Craft Scheduler Thread - 29"                                                                 
[22:31:35 WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing tas
k 5118                                                                                                                             
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Asynchronous player kick!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:219)
        at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:90)
        at fr.xephi.authme.process.Management$5.run(Management.java:81)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```
I got the similar issue. In my case that was when testing players that use one IP. Player `sas` connected while `player2` with the same IP was already logged in.

**Comment by Xephi** [comment]
Ok I've already find the problem, I'll fix it shortly
