### ISSUE TITLE
phpBB 3.1.5 and PHPBB encryption isn't the same

### ISSUE THREAD

**Issue by DanielRamosAcosta** [Xephi/AuthMeReloaded#150]
I've created a phpBB forum and created some additional columns to have separated data for Authme. I also did it for the password and they're not the same... here is a screenshot of the mysql table:

http://i.imgur.com/JKlj4df.jpg

As you can see, the "user_password" and the "athme_password" columns don't match. In the following link is my config.yml:
http://pastebin.com/9njenuG8

Thanks a lot.

**Comment by Xephi** [comment]
it looks they had changed the current encryption T.T looking in

**Comment by DanielRamosAcosta** [comment]
Thanks! <33

**Comment by sgdc3** [comment]
The phpbb new hash method is vwry complex

**Comment by sgdc3** [comment]
@DanielRamosAcosta Can you register a test user with a defined password like 12345 and tell me the 2 hash codes?

**Comment by DanielRamosAcosta** [comment]
Here are some:
| 123456   | $2y$10$DGtaykQaysA6Rhg5b0ZwZ.f5yOmhMIsVSPBap5qYitUlhvTUUWlve |
|----------|--------------------------------------------------------------|
| diamond  | $2y$10$n5v80zhvgzCNpUmhc/5qCeuUCAjc4Urt4A2tWV42eP1uW5tEFD2ZG |
| ruby123  | $2y$10$DXrX7T.VWSSbeDPZyKm3o.JjV3Qm9EfnCx0uD4A8dkb5HIUOs/AD. |
| sapphire | $2y$10$pcu1Wo0xx.F0.3Bvl2qf0OCfx9X3akYzwYa/pyGNRVTiJcIgGRYLK |

**Comment by Xephi** [comment]
where is the salt stored ?

**Comment by DanielRamosAcosta** [comment]
In the "user_form_salt" column, under the "phpbb_users" table.

**Comment by Xephi** [comment]
Thanks !

**Comment by Xephi** [comment]
Added ! Can you please try latest devbuild : http://ci.xephi.fr/job/AuthMeReloaded/ and set passwordHash to BCRYPT2Y in your authme config ?

**Comment by DanielRamosAcosta** [comment]
Thanks! But I get some exceptions:
```
>authme changepassword Duning papaya
[02:58:56 WARN]: Unexpected exception while parsing console command "authme changepassword Duning papaya"
org.bukkit.command.CommandException: Unhandled exception executing command 'authme' in plugin AuthMe v5.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640) ~[spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:626) [spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:411) [spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: Invalid salt revision
        at fr.xephi.authme.security.crypts.BCRYPT.hashpw(BCRYPT.java:399) ~[?:?]
        at fr.xephi.authme.security.crypts.BCRYPT2Y.getHash(BCRYPT2Y.java:12) ~[?:?]
        at fr.xephi.authme.security.PasswordSecurity.getHash(PasswordSecurity.java:121) ~[?:?]
        at fr.xephi.authme.commands.AdminCommand.onCommand(AdminCommand.java:439) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-74e8786-a3cb1bc]
        ... 8 more
```

Here is the new config I'm using: https://gist.github.com/dd52e51e037dedf5598a
I changed the password manually in the database and I can't login either.

Thanks!

**Comment by sgdc3** [comment]
Incompatible salt type :/ @Xephi now the salt column contains both MD5 and Bycrypt mixed salt. You need to split them first.

**Comment by Xephi** [comment]
Can you try with latest build plz ?

**Comment by DanielRamosAcosta** [comment]
Sorry for the delay, but for these days I wasn't at home...
I still don't get the same password hash

| Password | phpBB | Authme Hash (BCRYPT2Y) |
|----------|------------------------------------------------------------------|------------------------------------------------------------------|
| 123456 | ``$2y$10$XLe9mqO5vBdNyl/0taQgdeUnXNxxluVDPT0NsO5rnX2s/8R757Geu`` | ``$2y$10$b15cb6473c088f9533d6auIvStv1RsSPS6s069YPrfsidiSdCecxi`` |
| markdown | ``$2y$10$uGyT/S4634qpmL8cQ/IYWu0LPNQtI0xjnFiKj4mUdHIg8sAbv4rai`` | ``$2y$10$58ea41480703a66d8ae8fOnK7sViZDmu62odSp.R9LcqUV49USLz.`` |
| xephi1 | ``$2y$10$mFhEJs4FDI5qr2TNTQosQesXewdfi8lvLza/9arYKVHTkNMhWzgQy`` | ``$2y$10$548ed55b5f123e1401b13uMPCe8qfa4REEePLa65.Y5LENSFHXhVq`` |
| sgdc31 | ``$2y$10$3a0eI6DEdMdZbTZY.vy/q.y68K6J39UlYoWJ.WHU30CK8yVPWb0Yy`` | ``$2y$10$8d741f894e442c8ef25e8eDmTJyJIp00cW6PDQphDMOoJ.fHn7SYO`` |

Salt is: ``17ec4425180ea109``
Screenshot of the the entry: http://i.imgur.com/pXOhwP6.png
Here is the config.yml: https://gist.github.com/9952574a70e6d6c50af7

**Comment by DanielRamosAcosta** [comment]
Any news?

**Comment by sgdc3** [comment]
@DanielRamosAcosta The news is that @Xephi isn't avariable these days xD

**Comment by DanielRamosAcosta** [comment]
Ohhh ok xD

**Comment by Xephi** [comment]
Salt is stored in database, but it's the same salt for each user? :O

**Comment by DanielRamosAcosta** [comment]
Nope is not the same! http://i.imgur.com/3MqnhcG.png

**Comment by Xephi** [comment]
okok, i'll push a fix sooly

**Comment by sgdc3** [comment]
@DanielRamosAcosta @Xephi BUMP

**Comment by DanielRamosAcosta** [comment]
Hi, I'm so sorry for the late answer. I joined the university classes and I've been very bussy lately. I finish exams in february, then I'll come back to this.

Greetings!

**Comment by sgdc3** [comment]
Ok, good luck! ;)

**Comment by DanielRamosAcosta** [comment]
Thanks! :D

**Comment by Giulio1708** [comment]
News?

**Comment by dboecker** [comment]
@Xephi @sgdc3 Tried and it works here too (current dev version 5.2#887 + phpBB 3.1.8) :+1: Thanks a lot!

**Comment by sgdc3** [comment]
Thanks ;)
