### ISSUE TITLE
BungeeAuthMeBridge broke with latest updates.

### ISSUE THREAD

**Issue by JunkyBulgaria** [Xephi/AuthMeReloaded#162]
That's the error log, using latest AuthMe and AuthMeBridge v1.4.1
``
[05:36:21 WARN]: [AuthMeBridge] Task #283 for AuthMeBridge v1.4.1 generated an exception
java.lang.IncompatibleClassChangeError: Expected static method fr.xephi.authme.api.API.isAuthenticated(Lorg/bukkit/entity/Player;)Z
        at com.crylegend.authmebridge.AuthMeBridgeListener$1.run(AuthMeBridgeListener.java:47) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-6d16e64-bf4818b]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-6d16e64-bf4818b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot.jar:git-Spigot-6d16e64-bf4818b]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-6d16e64-bf4818b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-6d16e64-bf4818b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-6d16e64-bf4818b]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
``

**Comment by JunkyBulgaria** [comment]
nevermind, seems to be a different author, sorry

**Comment by sgdc3** [comment]
@JunkyBulgaria I can help you anyway, which version of AuthMe are you using?

**Comment by JunkyBulgaria** [comment]
latest
