### ISSUE TITLE
Latest build doesn't check for restricted symbols

### ISSUE THREAD

**Issue by VladStarr** [Xephi/AuthMeReloaded#176]
Hi.

I'm using the latest build of your plugin.
I've noticed that players with restricted symbols in their name can join the server.
AuthMe does not check for regex in config.

Here's the log

[19:25:46] [User Authenticator #23/INFO]: UUID of player максим is 1fe40771-057c-35c1-b780-045b07c98ec1
[19:25:46] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to AuthMe v5.0-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerList.attemptLogin(PlayerList.java:456) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at protocolsupport.protocol.transformer.handlers.AbstractLoginListener.b(AbstractLoginListener.java:104) [ProtocolSupport.jar:?]
	at protocolsupport.protocol.transformer.handlers.AbstractLoginListener.c(AbstractLoginListener.java:63) [ProtocolSupport.jar:?]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:871) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at fr.xephi.authme.listener.AuthMePlayerListener.onPlayerLogin(AuthMePlayerListener.java:471) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor381.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	... 13 more

**Comment by sgdc3** [comment]
Can you try it without protocol support?

**Comment by VladStarr** [comment]
Okay, i'll try.

**Comment by VladStarr** [comment]
The issue is still actual.
I've deleted ProtocolSupport and now i'm having this error

[21:14:12] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to AuthMe v5.0-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerList.attemptLogin(PlayerList.java:456) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:118) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:871) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at fr.xephi.authme.listener.AuthMePlayerListener.onPlayerLogin(AuthMePlayerListener.java:471) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[java8.jar:git-PaperSpigot-6d0a86a-53fac9f]
	... 13 more

**Comment by sgdc3** [comment]
@VladStarr try now :)

**Comment by VladStarr** [comment]
@sgdc3 works fine, thanks!
