### ISSUE TITLE
Changepassword error

### ISSUE THREAD

**Issue by VladStarr** [Xephi/AuthMeReloaded#190]
Hi. I'm using the latest build of plugin. (#144)
When i try to use /changepassword, plugin throws an error.

```
[15:58:08] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'changepassword' in plugin AuthMe v5.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[java8.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[java8.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[java8.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [java8.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [java8.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [java8.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [java8.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [java8.jar:git-Spigot-fdc1440-53fac9f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [java8.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [java8.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [java8.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [java8.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [java8.jar:git-Spigot-fdc1440-53fac9f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IllegalStateException: PasswordEncryptionEvent cannot be triggered asynchronously from primary server thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) ~[java8.jar:git-Spigot-fdc1440-53fac9f]
	at fr.xephi.authme.security.PasswordSecurity.getHash(PasswordSecurity.java:122) ~[?:?]
	at fr.xephi.authme.commands.ChangePasswordCommand.onCommand(ChangePasswordCommand.java:71) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[java8.jar:git-Spigot-fdc1440-53fac9f]
	... 15 more
```

**Comment by JunkyBulgaria** [comment]
confirm, same here. using MySQL as db source.
```
[19:10:45] [Server thread/INFO]: Junky issued server command: /changepassword
[19:10:52] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'changepassword' in plugin AuthMe v5.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[hysteria.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[hysteria.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[hysteria.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165) [hysteria.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000) [hysteria.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [hysteria.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [hysteria.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [hysteria.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [hysteria.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:771) [hysteria.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [hysteria.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [hysteria.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [hysteria.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.IllegalStateException: PasswordEncryptionEvent cannot be triggered asynchronously from primary server thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) ~[hysteria.jar:git-PaperSpigot-6d0a86a-53fac9f]
	at fr.xephi.authme.security.PasswordSecurity.getHash(PasswordSecurity.java:122) ~[?:?]
	at fr.xephi.authme.commands.ChangePasswordCommand.onCommand(ChangePasswordCommand.java:71) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[hysteria.jar:git-PaperSpigot-6d0a86a-53fac9f]
	... 15 more
```

**Comment by sgdc3** [comment]
can you check this version? http://ci.xephi.fr/job/DEVBUILD-ONLY/

**Comment by VladStarr** [comment]
Can't check, latest build tries to connect to the localhost, but I have my db on other server. Seems that plugin ignores config value.

**Comment by sgdc3** [comment]
Ok, thanks, I will fix it ;)

**Comment by JunkyBulgaria** [comment]
not fixed, error does not appear but password does not update.

**Comment by sgdc3** [comment]
@VladStarr Fixed, can you test and close the issue?
