### ISSUE TITLE
AsyncronousJoin error

### ISSUE THREAD

**Issue by VladStarr** [Xephi/AuthMeReloaded#211]
Hi. Build #214.

```
[11:57:39] [Server thread/INFO]: emTM[/93.157.144.26:6243] logged in with entity id 4448 at ([world]2073.5, 64.0, -1267.5)
[11:57:39] [Craft Scheduler Thread - 4/WARN]: java.lang.NullPointerException
[11:57:39] [Craft Scheduler Thread - 4/WARN]: 	at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:181)
[11:57:39] [Craft Scheduler Thread - 4/WARN]: 	at fr.xephi.authme.process.Management$5.run(Management.java:79)
[11:57:39] [Craft Scheduler Thread - 4/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[11:57:39] [Craft Scheduler Thread - 4/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[11:57:39] [Craft Scheduler Thread - 4/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[11:57:39] [Craft Scheduler Thread - 4/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[11:57:39] [Craft Scheduler Thread - 4/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Dimatert9** [comment]
+

[14:35:55 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[14:35:55 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[14:35:55 WARN]:        at java.lang.Thread.run(Thread.java:745)
[14:35:56 INFO]: UUID of player TripleRhu is 37f7a281-13c7-3f60-9d99-3131e61a4b24
[14:35:56 INFO]: TripleRhu[/178.167.31.197:55077] logged in with entity id 7 at ([world]10.5, 21.0, 0.5)
[14:35:56 WARN]: java.lang.NullPointerException
[14:35:56 WARN]:        at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:181)
[14:35:56 WARN]:        at fr.xephi.authme.process.Management$5.run(Management.java:79)
[14:35:56 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[14:35:56 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[14:35:56 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[14:35:56 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[14:35:56 WARN]:        at java.lang.Thread.run(Thread.java:745)
[14:35:56 INFO]: UUID of player DADILERON is 43dae01e-9529-3f84-89e8-7f40181e6b41
[14:35:56 INFO]: DADILERON[/46.160.165.118:48072] logged in with entity id 8 at ([world]10.5, 21.0, 0.5)
[14:35:56 INFO]: UUID of player keeler is 73c3edc5-04e3-3331-be00-1658ecf4a563
[14:35:56 INFO]: keeler[/94.154.72.213:48447] logged in with entity id 9 at ([world]10.5, 21.0, 0.5)
[14:35:56 WARN]: java.lang.NullPointerException
[14:35:56 WARN]:        at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:181)
[14:35:56 WARN]:        at fr.xephi.authme.process.Management$5.run(Management.java:79)
[14:35:56 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[14:35:56 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[14:35:56 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[14:35:56 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[14:35:56 WARN]:        at java.lang.Thread.run(Thread.java:745)
[14:35:57 INFO]: UUID of player DJINI is a0549dc2-9c03-3e73-90f2-d7fe1fdb4ff3
[14:35:57 INFO]: DJINI[/176.215.157.112:35235] logged in with entity id 10 at ([world]10.5, 21.0, 0.5)
[14:35:57 WARN]: java.lang.NullPointerException
[14:35:57 WARN]:        at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:181)
[14:35:57 WARN]:        at fr.xephi.authme.process.Management$5.run(Management.java:79)
[14:35:57 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[14:35:57 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[14:35:57 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[14:35:57 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[14:35:57 WARN]:        at java.lang.Thread.run(Thread.java:745)
[14:35:58 INFO]: [AuthMe] [AuthMe] 8875 logged in!

**Comment by sgdc3** [comment]
@VladStarr Fixed! Can you close this issue?
