### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Xofter** [Xephi/AuthMeReloaded#213]
[18:19:56] [Server thread/INFO]: JamCraft[/78.62.229.170:59601] logged in with entity id 4646600 at ([world]-453.5, 1.0, -267.5)
[18:19:56] [Craft Scheduler Thread - 2245/WARN]: Exception in thread "Craft Scheduler Thread - 2245" 
[18:19:56] [Craft Scheduler Thread - 2245/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing task 45594711
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:67)
	at fr.xephi.authme.process.Management$5.run(Management.java:81)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by sgdc3** [comment]
Plugin version?

**Comment by Xofter** [comment]
#1​50

**Comment by sgdc3** [comment]
can you test 151?

**Comment by sgdc3** [comment]
Do a backup before

**Comment by sgdc3** [comment]
@Xofter Fixed, can you test latest dev build?

**Comment by sgdc3** [comment]
http://ci.xephi.fr/job/DEVBUILD-ONLY/
