### ISSUE TITLE
Email recovery doesn't work

### ISSUE THREAD

**Issue by NIK220V** [Xephi/AuthMeReloaded#220]
[20:15:29] [Craft Scheduler Thread - 5/WARN]: Exception in thread "Craft Scheduler Thread - 5" 
[20:15:29] [Craft Scheduler Thread - 5/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing task 56
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/sun/mail/util/MailLogger
	at javax.mail.Session.initLogger(Session.java:226)
	at javax.mail.Session.<init>(Session.java:210)
	at javax.mail.Session.getInstance(Session.java:247)
	at fr.xephi.authme.SendMailSSL$1.run(SendMailSSL.java:66)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.sun.mail.util.MailLogger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more

**Comment by DNx5** [comment]
what is your Java version?

**Comment by NIK220V** [comment]
Java 8.
This error is on 5.0 beta 3.
I updated to #230
and now with config like this:
Email:
    # Email SMTP server host
    mailSMTP: smtp-pulse.com
    # Email SMTP server port
    mailPort: 465
    # Email account that send the mail
    mailAccount: 'myaccount@gmail.com'
    # Email account password
    mailPassword: 'xxxxxxxxx'
    # Custom SenderName, that replace the mailAccount name in the email
    mailSenderName: 'myname@gmail.com'
    # Random password length
    RecoveryPasswordLength: 8
    # Email subject of password get
    mailSubject: 'Your new AuthMe Password'
    # Email text here
    mailText: 'Dear <playername>, <br /><br /> This is your new AuthMe password for the server <br /><br /> <servername> : <br /><br /> <generatedpass><br /><br />Do not forget to change password after login! <br /> /changepassword <generatedpass> newPassword'
    # Like maxRegPerIp but with email
    maxRegPerEmail: 1
    # Recall players to add an email ?
    recallPlayers: false
    # Delay in minute for the recall scheduler
    delayRecall: 5
    # Blacklist these domains for emails
    emailBlacklisted:
    - 10minutemail.com
    # WhiteList only these domains for emails
    emailWhitelisted: []

It isn't showing any errors but does nothing.

**Comment by sgdc3** [comment]
Ok now it loads the java library correctly but the send method doesn't work.

**Comment by NIK220V** [comment]
So,  error is in my config or in the plugin?

**Comment by sgdc3** [comment]
idk, we need to add more error messages to know where's the problem

**Comment by NIK220V** [comment]
Can i help with something or should i just wait next build?

**Comment by sgdc3** [comment]
If you know java you can help us :)

**Comment by NIK220V** [comment]
I think i found one more bug.
OP permission still work even if not logged in.
e.g. plugin which requires OP to give you cobblestone in inventory will give cobblestone into the inventory of even not logged in person.

**Comment by sgdc3** [comment]
Can you open a new issue about?

**Comment by sgdc3** [comment]
@NIK220V

**Comment by NIK220V** [comment]
So, what's actually with adding more messages?
I really want email recovery to work.

**Comment by sgdc3** [comment]
what do you mean?

**Comment by sgdc3** [comment]
ah ok, you mean error messages ;)
