### ISSUE TITLE
shutting down server error [Mysql]

### ISSUE THREAD

**Issue by Xofter** [Xephi/AuthMeReloaded#232]

**Comment by Xofter** [comment]
[04:23:16] [pool-38-thread-225/WARN]: AuthMeMYSQLPool - Connection null, created Oct 10, 04:21:00.181, last release 136579ms ago, REMOVED marked as broken because of SQLSTATE(08S01), ErrorCode(0)
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 6 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3082) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2968) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3516) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61) ~[AuthMe-5.1-SNAPSHOT.jar:?]
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.executeUpdate(HikariPreparedStatementProxy.java) [AuthMe-5.1-SNAPSHOT.jar:?]
	at fr.xephi.authme.datasource.MySQL.setUnlogged(MySQL.java:890) [AuthMe-5.1-SNAPSHOT.jar:?]
	at fr.xephi.authme.datasource.CacheDataSource$12.run(CacheDataSource.java:343) [AuthMe-5.1-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:203) ~[?:1.8.0_51]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_51]
	at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:114) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:161) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:189) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2526) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2979) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	... 16 more

**Comment by sgdc3** [comment]
can you provide your configuration?

**Comment by Xofter** [comment]
The mysql works perfectly fine, everyone (90 players) seems to log in just fine, i only get that error when shutting down the server.
DataSource:
  mySQLColumnName: username
  mySQLTablename: authme
  mySQLUsername: root
  backend: mysql
  mySQLColumnLastLogin: lastlogin
  mySQLDatabase: authme
  mySQLPort: '3306'
  mySQLColumnIp: ip
  mySQLHost: 127.0.0.1
  mySQLColumnPassword: password
  mySQLPassword: ***** hidden password *******
  caching: true
  mySQLlastlocX: x
  mySQLlastlocY: y
  mySQLlastlocZ: z
  mySQLlastlocWorld: world
  mySQLColumnEmail: email
  mySQLColumnId: id
  mySQLColumnLogged: isLogged
  mySQLRealName: realname
  mySQLMaxConections: 25
GroupOptions:
  UnregisteredPlayerGroup: ''
  RegisteredPlayerGroup: ''
  Permissions:
    PermissionsOnJoin: []

**Comment by Trojaner25** [comment]
>Caused by: java.net.SocketException: Socket closed
Is your MySQL server running? Does something interupt the connection (a firewall?)?

**Comment by sgdc3** [comment]
it happens only on server shutdown he said

**Comment by sgdc3** [comment]
@Trojaner25

**Comment by Xephi** [comment]
Do you got the same problem if you kick your players before shutting down the server ?

**Comment by Xephi** [comment]
Huum, i think i've found a way to fix this, can you please check in latest build ?

**Comment by Xofter** [comment]
Seems fixed thanks

**Comment by sgdc3** [comment]
@Xofer can you close the issue ;)

**Comment by sgdc3** [comment]
?

**Comment by xofer** [comment]
@sgdc3 you mean @Xofter :)
