### ISSUE TITLE
PlayerQuit error

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#245]
[16:13:12] [Server thread/INFO]: [-] Wolfimolfi12
[16:13:12] [Craft Scheduler Thread - 1820/WARN]: Exception in thread "Craft Scheduler Thread - 1820" 
[16:13:12] [Craft Scheduler Thread - 1820/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.1-SNAPSHOT generated an exception while executing task 3921010
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at fr.xephi.authme.process.quit.AsyncronousQuit.process(AsyncronousQuit.java:59)
	at fr.xephi.authme.process.Management$4.run(Management.java:68)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by sgdc3** [comment]
Are you using latest build? @andris155

**Comment by andris155** [comment]
Use: AuthMe 5.1 Snapshot #163
