### ISSUE TITLE
Error message on start server

### ISSUE THREAD

**Issue by CooCoo3** [Xephi/AuthMeReloaded#247]
[16:31:54] [Craft Scheduler Thread - 15/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.1-SNAPSHOT generated an exception while executing task 113
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:185)
	at fr.xephi.authme.process.Management$5.run(Management.java:79)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by Xephi** [comment]
Can you copy/paste the full starting server log (paste on pastebin/zerobin/etc...)

**Comment by CooCoo3** [comment]
http://pastebin.com/z1pjLwar

**Comment by sgdc3** [comment]
@Xephi

**Comment by Xephi** [comment]
Fixed https://github.com/Xephi/AuthMeReloaded/commit/7824131cec0ae59b8f661f2f3a7a0cb5bae83134
