### ISSUE TITLE
warn on join player

### ISSUE THREAD

**Issue by Cronosus** [Xephi/AuthMeReloaded#25]
[21:22:42] [Server thread/WARN] [/]: java.lang.IllegalStateException: Unable to find method getTypeId ([]).
[21:22:42] [Server thread/WARN] [/]: 	at com.comphenix.attribute.NbtFactory.getMethod(NbtFactory.java:817)
[21:22:42] [Server thread/WARN] [/]: 	at com.comphenix.attribute.NbtFactory.getMethod(NbtFactory.java:816)
[21:22:42] [Server thread/WARN] [/]: 	at com.comphenix.attribute.NbtFactory.<init>(NbtFactory.java:366)
[21:22:42] [Server thread/WARN] [/]: 	at com.comphenix.attribute.NbtFactory.get(NbtFactory.java:343)
[21:22:42] [Server thread/WARN] [/]: 	at com.comphenix.attribute.NbtFactory.getCraftItemStack(NbtFactory.java:603)
[21:22:42] [Server thread/WARN] [/]: 	at com.comphenix.attribute.Attributes.<init>(Attributes.java:244)
[21:22:42] [Server thread/WARN] [/]: 	at fr.xephi.authme.cache.backup.FileCache.createCache(FileCache.java:104)
[21:22:42] [Server thread/WARN] [/]: 	at fr.xephi.authme.listener.AuthMePlayerListener.onPlayerJoin(AuthMePlayerListener.java:675)
[21:22:42] [Server thread/WARN] [/]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:22:42] [Server thread/WARN] [/]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[21:22:42] [Server thread/WARN] [/]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:22:42] [Server thread/WARN] [/]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[21:22:42] [Server thread/WARN] [/]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
[21:22:42] [Server thread/WARN] [/]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:22:42] [Server thread/WARN] [/]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
[21:22:42] [Server thread/WARN] [/]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
[21:22:42] [Server thread/WARN] [/]: 	at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(ServerConfigurationManager.java:352)
[21:22:42] [Server thread/WARN] [/]: 	at net.minecraft.server.management.ServerConfigurationManager.a(ServerConfigurationManager.java:218)
[21:22:42] [Server thread/WARN] [/]: 	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:173)
[21:22:42] [Server thread/WARN] [/]: 	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:448)
[21:22:42] [Server thread/WARN] [/]: 	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21)
[21:22:42] [Server thread/WARN] [/]: 	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11)
[21:22:42] [Server thread/WARN] [/]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[21:22:42] [Server thread/WARN] [/]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[21:22:42] [Server thread/WARN] [/]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[21:22:42] [Server thread/WARN] [/]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[21:22:42] [Server thread/WARN] [/]: 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[21:22:42] [Server thread/WARN] [/]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[21:22:42] [Server thread/WARN] [/]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[21:22:42] [Server thread/WARN] [/]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[21:22:42] [Server thread/WARN] [/]: 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[21:22:42] [Server thread/WARN] [/]: 	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[21:22:42] [Server thread/WARN] [/]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[21:22:42] [Server thread/WARN] [/]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[21:22:42] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
[21:22:42] [Server thread/WARN] [/]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
[21:22:42] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
[21:22:42] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[21:22:42] [Server thread/WARN] [/]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by atomic7777** [comment]
I have the same issue, but I also have it in my own plugin when I use comphenix NbtFactory.
I suppose it's not related to Authme, but it's comphenix.attribute.NbtFactory not working properly with Cauldron.
It's a big issu for me, because Cauldron 1.7.10 is still alive, still "maintained" by someone, and we don't have an alternative right now

**Comment by mmance** [comment]
I am also having this issue on 1.7.10 for Cauldron.  Other then the warning, the plugin seems to be working as expected.

**Comment by Xephi** [comment]
Fixed https://github.com/Xephi/AuthMeReloaded/commit/514d5bfe6e7f5e7f0f2ca01b1923ec9bcfe1c0dd

**Comment by ArcasCZ** [comment]
Where i can download this new version?

**Comment by Xephi** [comment]
http://ci.xephi.fr

**Comment by sgdc3** [comment]
Here in Italy your ci appears offline!

**Comment by Xephi** [comment]
Host down u.U ticket open on hoster service, sorry x)
