### ISSUE TITLE
lost com.sun.mail.util.MailLogger when sending a recovery email..

### ISSUE THREAD

**Issue by kxjhwbb** [Xephi/AuthMeReloaded#261]
Thank you ~   sure my email setting is ok (it works in authme 3.5)

Caused by: java.lang.ClassNotFoundException: com.sun.mail.util.MailLogger
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 9 more

I try to copy the folder /com/ to 5.0 from authme 3.5 , still not work..
show me this:
[15:01:52] [Craft Scheduler Thread - 1/INFO]: Some error occured while trying to send a mail to xxx@gmail.com

**Comment by sgdc3** [comment]
Can you try latest build at http://ci.xephi.fr/job/AuthMeReloaded-Dev/ ? Thanks :)

**Comment by sgdc3** [comment]
@kxjhwbb ? :)

**Comment by Xephi** [comment]
Fixed
