### ISSUE TITLE
Timed out random error

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#268]
Authme: 5.1 dev build180

[10:01:07] [Server thread/INFO]: bala lost connection: Timed out
[10:01:07] [Server thread/INFO]: [-] bala
[10:01:07] [Craft Scheduler Thread - 817/WARN]: Exception in thread "Craft Scheduler Thread - 817" 
[10:01:07] [Craft Scheduler Thread - 817/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.1-SNAPSHOT generated an exception while executing task 823909
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at fr.xephi.authme.process.quit.AsyncronousQuit.process(AsyncronousQuit.java:59)
	at fr.xephi.authme.process.Management$6.run(Management.java:88)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by Xephi** [comment]
Can you maybe test latest AuthMeDev build ?

**Comment by andris155** [comment]
Yes I started testing.

**Comment by andris155** [comment]
8.11 11:14:38 [Server] INFO [AuthMe] CrafterStudio10 used the wrong password
18.11 11:14:38 [Disconnect] User CrafterStudio10 has disconnected, reason: Wrong password
18.11 11:14:38 [Server] INFO CrafterStudio10
18.11 11:14:38 [Server] WARN Exception in thread "Craft Scheduler Thread - 457" 
18.11 11:14:38 [Server] WARN handleDisconnection() called twice
18.11 11:14:38 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.1-SNAPSHOT generated an exception while executing task 399903
18.11 11:14:38 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
18.11 11:14:38 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
18.11 11:14:38 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
18.11 11:14:38 [Server] INFO at java.lang.Thread.run(Unknown Source)
18.11 11:14:38 [Server] INFO Caused by: java.lang.NullPointerException
18.11 11:14:38 [Server] INFO at fr.xephi.authme.process.quit.AsyncronousQuit.process(AsyncronousQuit.java:59)
18.11 11:14:38 [Server] INFO at fr.xephi.authme.process.Management$6.run(Management.java:88)
18.11 11:14:38 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
18.11 11:14:38 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
18.11 11:14:38 [Server] INFO ... 3 more

**Comment by sgdc3** [comment]
Can you try latest -dev build?

**Comment by sgdc3** [comment]
@andris155
