### ISSUE TITLE
AsynchronousJoin null pointer exception

### ISSUE THREAD

**Issue by JHXSMatthew** [Xephi/AuthMeReloaded#299]
That happens from time to time when more than 20 players join at the same time.

[19:49:27 WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.1-SNAPSHOT-b182 generated an exception while executing task 379
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at fr.xephi.authme.process.join.AsynchronousJoin.process(AsynchronousJoin.java:257)
        at fr.xephi.authme.process.Management$5.run(Management.java:76)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by Xephi** [comment]
https://github.com/AuthMe-Team/AuthMeReloaded/commit/0d1cf8c7e234a5235d599792c6e072dde8f1afc1
