### ISSUE TITLE
Server stop WARN.

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#383]
http://ci.xephi.fr/job/AuthMeReloaded-Dev/586/
[02:06:39] [Thread-16/WARN]: Exception in thread "Thread-16" 
[02:06:39] [Thread-16/WARN]: java.lang.IllegalStateException: Asynchronous player kick!
[02:06:39] [Thread-16/WARN]: 	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[02:06:39] [Thread-16/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:215)
[02:06:39] [Thread-16/WARN]: 	at fr.xephi.authme.listener.AuthMeServerStop.run(AuthMeServerStop.java:20)

**Comment by Xephi** [comment]
Can you turn off in config.yml > Security >kickPlayerBeforeStopping, and tell me if you keep getting this error?

**Comment by Xephi** [comment]
Fixed

**Comment by andris155** [comment]
Thanks!
