### ISSUE TITLE
Exception in thread "Craft Scheduler Thread - 2421" 

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#389]
[21:45:02] [Server thread/INFO]: [-] szsoma22
[21:45:02] [Craft Scheduler Thread - 2421/WARN]: Exception in thread "Craft Scheduler Thread - 2421" 
[21:45:02] [Craft Scheduler Thread - 2421/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.2-SNAPSHOT-b586 generated an exception while executing task 6533616
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at fr.xephi.authme.process.quit.AsynchronousQuit.process(AsynchronousQuit.java:66)
	at fr.xephi.authme.process.Management$6.run(Management.java:87)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by DardBrinza** [comment]
Exactly the same error :)

**Comment by Xephi** [comment]
Can you please try latest dev build ?

**Comment by sgdc3** [comment]
@andris155

**Comment by andris155** [comment]
This error only occurred a couple of times, but since then I've never seen it again.
