### ISSUE TITLE
[BUG] Player can change their email with out permission: 'authme.email.change'

### ISSUE THREAD

**Issue by KokeCacao** [Xephi/AuthMeReloaded#437]
They can use /email add [email] to change their email.

For example:
/email add email@a.com
/email add email@b.com
The player will change email from email@a.com to email@b.com with out permission 'authme.email.change'!

if
/email add email@a.com
/email add email@a.com
The plugin will return: 'You have exceeded the maximum number of registration for your connection!'

The plugin did not check if the email database is empty.
Please fix that soon.

**Comment by ljacqu** [comment]
Pushed some changes on a separate branch. I still need to test it. I think I will only have time next weekend. :(

**Comment by KokeCacao** [comment]
You can also check that if the email is added by other users.
It is optional.

**Comment by sgdc3** [comment]
What do you mean?

**Comment by ljacqu** [comment]
@KokeCacao Thanks for the review. I will also add a check for uniqueness

**Comment by KokeCacao** [comment]
A weekend has passed... Have you release the new build?

**Comment by DNx5** [comment]
development build
http://ci.xephi.fr/job/AuthMeReloaded

**Comment by KokeCacao** [comment]
#686

[13:33:18] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.2-SNAPSHOT-b686
[13:33:18] [Server thread/INFO]: [AuthMe] Loading Configuration File...
[13:33:18] [Server thread/WARN]: [AuthMe] Remove Email.mailText from config, we now use the email.html file
[13:33:18] [Server thread/WARN]: [AuthMe] Merged new Config Options - I'm not an error, please don't report me
[13:33:18] [Server thread/WARN]: [AuthMe] Please check your config.yml file for new configs!
[13:33:18] [Server thread/INFO]: [AuthMe] Set Language to: en
[13:33:18] [Server thread/INFO]: [AuthMe] Connection arguments loaded, Hikari ConnectionPool ready!
[13:33:18] [Server thread/INFO]: AuthMeMYSQLPool - is starting.
[13:33:18] [Server thread/INFO]: [AuthMe] MySQL Setup finished
[13:33:18] [Server thread/ERROR]: Error occurred while enabling AuthMe v5.2-SNAPSHOT-b686 (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.build(Lcom/google/common/cache/CacheLoader;)Lcom/google/common/cache/LoadingCache;
	at fr.xephi.authme.datasource.CacheDataSource.<init>(CacheDataSource.java:48) ~[?:?]
	at fr.xephi.authme.AuthMe.setupDatabase(AuthMe.java:613) ~[?:?]
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:226) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:git-Spigot-1649]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-Spigot-1649]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot.jar:git-Spigot-1649]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot.jar:git-Spigot-1649]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1649]
[13:33:18] [Server thread/INFO]: [AuthMeBridge] Enabling AuthMeBridge v1.5
[13:33:18] [Server thread/INFO]: [AuthMeBridge] Hello world
and then
[13:34:02] [Server thread/INFO]: Koke_Cacao issued server command: /login
[13:34:02] [Server thread/ERROR]: [AuthMe] AuthMe command handler is not available
[13:34:02] [Server thread/INFO]: Koke_Cacao issued server command: /login xxxxxxx
[13:34:02] [Server thread/ERROR]: [AuthMe] AuthMe command handler is not available

**Comment by ljacqu** [comment]
Unrelated. My changes aren't in the development build yet. I landed in the hospital on Friday and had surgery on Saturday, so my weekend plans were postponed :P

**Comment by KokeCacao** [comment]
Well, I wish you a good health. XD

**Comment by games647** [comment]
@KokeCacao Which minecraft version do you use?

**Comment by games647** [comment]
The guava library version changed from 1.7 to 1.8. We might should build something like [this](https://github.com/dmulloy2/ProtocolLib/blob/master/ProtocolLib/src/main/java/com/comphenix/protocol/utility/SafeCacheBuilder.java)

**Comment by DNx5** [comment]
:worried:

**Comment by sgdc3** [comment]
Should we include guava as shaded maven library?

**Comment by ljacqu** [comment]
Personally I would prefer that if it's possible than using reflection. The smiley DNx5 posted says it all :P...

**Comment by sgdc3** [comment]
ok, sgdc3 gets in action... tomorrow xD

**Comment by ljacqu** [comment]
I haven't forgotten about this! Will be done within the next six days.

**Comment by ljacqu** [comment]
@KokeCacao This should be done now ^^ Sorry for the long wait. Can you give us some feedback whether this fixes the issue you've described?

**Comment by KokeCacao** [comment]
okey, I'll test for you.
The latest build?

**Comment by ljacqu** [comment]
Yes, please :)

**Comment by KokeCacao** [comment]
No method error.
onEnable.setupDatabase

spigot.1.7.10(procotohack)

**Comment by ljacqu** [comment]
Oh, yes. I think @sgdc3 is planning on handling this with #467. I completely forgot about this and focused on the email handling logic.

**Comment by sgdc3** [comment]
@ljacqu We can fix in 2 ways: shade guava into the jar (no pls xD +2Mb in the final jar) or compile the plugin under an old build of guava.

**Comment by sgdc3** [comment]
@ljacqu What do you think?

**Comment by ljacqu** [comment]
@KokeCacao The Guava issue should have been updated (via #467). Sorry for the wait/confusion

**Comment by ljacqu** [comment]
Closing—assuming that no answer for >2 weeks means it's OK.
