### ISSUE TITLE
BUG about issue #436

### ISSUE THREAD

**Issue by smartmadio** [Xephi/AuthMeReloaded#440]
I know SHA256 is better.But I really need it ,because Discuz uses SALTED2MD5 to store the password,if I want to sync password with Discuz I have to use SALTED2MD5,perhaps I'll have to delete the passwords and ask players to register again.

And during the test abuout issue #436  I found another bug: if I want to transform passwordhash from SALTED2MD5 to SHA256,it still won't work,too.

```
[20:22:14] [Craft Scheduler Thread - 14/WARN]: [AuthMe] Bcrypt checkpw() returned [IllegalArgumentException]: Invalid salt version
[20:22:14] [Craft Scheduler Thread - 14/WARN]: Exception in thread "Craft Scheduler Thread - 14" 
[20:22:14] [Craft Scheduler Thread - 14/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.2-SNAPSHOT-b682 generated an exception while executing task 249
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at fr.xephi.authme.security.HashUtils.hash(HashUtils.java:80)
	at fr.xephi.authme.security.HashUtils.md5(HashUtils.java:52)
	at fr.xephi.authme.security.crypts.IPB3.computeHash(IPB3.java:17)
	at fr.xephi.authme.security.crypts.SeparateSaltMethod.comparePassword(SeparateSaltMethod.java:22)
	at fr.xephi.authme.security.PasswordSecurity.compareWithAllEncryptionMethods(PasswordSecurity.java:72)
	at fr.xephi.authme.security.PasswordSecurity.comparePassword(PasswordSecurity.java:53)
	at fr.xephi.authme.process.login.AsynchronousLogin.process(AsynchronousLogin.java:142)
	at fr.xephi.authme.process.Management$1.run(Management.java:36)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

```

**Comment by ljacqu** [comment]
You can't _transform_ a hash to another hash. With the settings enabled, we will check the stored hash in the db against all our supported hash algo's. Only if a player logs in, we can hash the pw with the new hash algo and store it in the db.
I.e. if you leave supportOldPassword = true for one week in yout config, all players that log in during this week will have updated hashes.

I'll assign this to me and 
a) Fix the exception you received
b) Assert that conversion from sha-512 to salted2md5 works as expected

**Comment by smartmadio** [comment]
Yes,I know your meaning, a hash couldn'd be transformed into another and I know it's when player logs in ,it will try all hash algo.

As sha256 to saltedmd5 ,I've solved the problem using my way.

Thanks for fixing it.

**Comment by ljacqu** [comment]
Thanks for the report!
With the changes in the referenced commit I can now successfully "convert" from SHA256 to Salted2Md5. Please close this issue if there's nothing left to solve for this issue, or let me know what is missing. :)

**Comment by smartmadio** [comment]
Thank you.

**Comment by ljacqu** [comment]
Thanks for the feedback!
