### ISSUE TITLE
Bug/Errors with /login D:

### ISSUE THREAD

**Issue by Barrimor** [Xephi/AuthMeReloaded#462]
Hello, I tried to login on my server with one of my offline alts, then Authme thrown errors in console. You will find the log down.

I have a little idea about how it does that:
- I set max join / ip = 2 & max register / ip = 2 (I had already my main account + one of my alt connected before connecting the 3rd one)
- When I did /login it told me "Already authenticated"
- I also use AutoIn / AutoIn-Authme.
- I run the latest version of spigot (git-Spigot-db6de12-07c3001) for Minecraft 1.8.8.

EDIT: Nvm, it happened before I even /login. When I joined the server Authme thrown the error, I just figured it out in the console.

Btw: I wasn't supposed to be able to connect? I set max join / ip = 2...

[11:10:22 WARN]: Exception in thread "Craft Scheduler Thread - 84" 
[11:10:22 WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing task 3280
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Asynchronous player kick!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:214)
at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:90)
at fr.xephi.authme.process.Management$5.run(Management.java:81)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

**Comment by DNx5** [comment]
@Barrimor Update your AuthMe plugin

**Comment by sgdc3** [comment]
http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT.jar
