### ISSUE TITLE
Buildcraft doesn't work (Cauldron GUAVA Issue)

### ISSUE THREAD

**Issue by ScuroGuardiano** [Xephi/AuthMeReloaded#467]
Hi, I have problem with BuildCraft and AuthMe. Buildcraft Quarry doesn't work, I added buildcraft to unrestrictions, but it still doesn't work. I tried everything... I am using AuthMe Reloaded 5.0-beta3.
My server engine is KCauldron
My configuration file: http://pastebin.com/MNjDb0jh
Please help
PS: Sorry for my English, I am from Poland

**Comment by sgdc3** [comment]
Try latest build: http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT.jar

**Comment by ScuroGuardiano** [comment]
This version doesn't work:
[14:27:18] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.2-SNAPSHOT-b699
[14:27:18] [Server thread/INFO]: [AuthMe] Loading Configuration File...
[14:27:18] [Server thread/WARN]: [AuthMe] Remove Email.mailText from config, we now use the email.html file
[14:27:18] [Server thread/WARN]: [AuthMe] Merged new Config Options - I'm not an error, please don't report me
[14:27:18] [Server thread/WARN]: [AuthMe] Please check your config.yml file for new configs!
[14:27:18] [Server thread/INFO]: [AuthMe] Set Language to: en
[14:27:18] [Server thread/WARN]: [AuthMe] WARNING!!! The protectInventory feature requires ProtocolLib! Disabling it...
[14:27:18] [Server thread/INFO]: [AuthMe] SQLite driver loaded
[14:27:18] [Server thread/INFO]: [AuthMe] SQLite Setup finished
[14:27:18] [Server thread/ERROR]: Error occurred while enabling AuthMe v5.2-SNAPSHOT-b699 (Is it up to date?)
java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.build(Lguava10/com/google/common/cache/CacheLoader;)Lguava10/com/google/common/cache/LoadingCache;
	at fr.xephi.authme.datasource.CacheDataSource.<init>(CacheDataSource.java:48) ~[?:?]
	at fr.xephi.authme.AuthMe.setupDatabase(AuthMe.java:649) ~[?:?]
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:228) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:500) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:474) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:434) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:335) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

**Comment by sgdc3** [comment]
This is because cauldron isn't supported atm, i'll try to fix that...

**Comment by White6983** [comment]
Try 3.1 version ;) On 3.1+ unrestrictions don't work.

**Comment by sgdc3** [comment]
@ScuroGuardiano Ciao, dovremmo aver risolto! Prova questo jar: http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-legacy.jar

**Comment by KokeCacao** [comment]
@sgdc3 Although I have no idea what you talking about,
但是我還是會試壹試插件的, 謝謝`(*∩_∩*)′

**Comment by sgdc3** [comment]
We have fixed the issue, just download our -legacy jar from our jenkins

**Comment by ScuroGuardiano** [comment]
Still the same http://pastebin.com/hvpgmDxB :/

**Comment by sgdc3** [comment]
@games647 any ideas? ;)

**Comment by KokeCacao** [comment]
How is the progress

**Comment by sgdc3** [comment]
@KokeCacao It should work now, just download latest -legacy jar ;)

**Comment by KokeCacao** [comment]
`[06:13:42] [Server thread/INFO]: Koke_Cacao login successfully[m
[06:13:42] [User Authenticator #1/INFO]: UUID of player Koke_Cacao is ea8732b4-041a-3356-a132-e18d8b2d63c4
[06:13:42] [Server thread/ERROR]: [AuthMe] Unhandled exception occured in onPacketSending(PacketEvent) for AuthMe
java.lang.IllegalStateException: Override onPacketSending to get notifcations of sent packets!
	at com.comphenix.protocol.events.PacketAdapter.onPacketSending(PacketAdapter.java:316) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:638) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:614) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedProtocolInjector.packetQueued(ShadedProtocolInjector.java:312) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedProtocolInjector.onPacketSending(ShadedProtocolInjector.java:278) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector.processSending(ShadedChannelInjector.java:416) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector.access$500(ShadedChannelInjector.java:83) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector$6.handleScheduled(ShadedChannelInjector.java:382) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector$6.onMessageScheduled(ShadedChannelInjector.java:350) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelProxy$2.schedulingRunnable(ShadedChannelProxy.java:127) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedEventLoopProxy.execute(ShadedEventLoopProxy.java:95) [ProtocolLib.jar:?]
	at net.minecraft.server.v1_7_R4.NetworkManager.b(NetworkManager.java:151) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.NetworkManager.handle(NetworkManager.java:129) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerConnection.sendPacket(PlayerConnection.java:803) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerList.c(PlayerList.java:292) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerList.a(PlayerList.java:152) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.LoginListener.c(LoginListener.java:119) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.LoginListener.a(LoginListener.java:44) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1649]
[06:13:42] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo@53ad1f6a[
    action=0
    player=net.minecraft.util.com.mojang.authlib.GameProfile@10452989[id=ea8732b4-041a-3356-a132-e18d8b2d63c4,name=Koke_Cacao,properties={textures=[net.minecraft.util.com.mojang.authlib.properties.Property@46dea383]},legacy=false]
    gamemode=0
    ping=0
    username=Koke_Cacao
    timestamp=1456611222497
  ]

[06:13:42] [Server thread/ERROR]: [AuthMe] Unhandled exception occured in onPacketSending(PacketEvent) for AuthMe
java.lang.IllegalStateException: Override onPacketSending to get notifcations of sent packets!
	at com.comphenix.protocol.events.PacketAdapter.onPacketSending(PacketAdapter.java:316) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:638) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:614) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedProtocolInjector.packetQueued(ShadedProtocolInjector.java:312) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedProtocolInjector.onPacketSending(ShadedProtocolInjector.java:278) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector.processSending(ShadedChannelInjector.java:416) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector.access$500(ShadedChannelInjector.java:83) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector$6.handleScheduled(ShadedChannelInjector.java:382) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector$6.onMessageScheduled(ShadedChannelInjector.java:350) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelProxy$2.schedulingRunnable(ShadedChannelProxy.java:127) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedEventLoopProxy.execute(ShadedEventLoopProxy.java:95) [ProtocolLib.jar:?]
	at net.minecraft.server.v1_7_R4.NetworkManager.b(NetworkManager.java:151) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.NetworkManager.handle(NetworkManager.java:129) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerConnection.sendPacket(PlayerConnection.java:803) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerList.c(PlayerList.java:305) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerList.a(PlayerList.java:152) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.LoginListener.c(LoginListener.java:119) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.LoginListener.a(LoginListener.java:44) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1649]
[06:13:42] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo@13b41670[
    action=0
    player=net.minecraft.util.com.mojang.authlib.GameProfile@10452989[id=ea8732b4-041a-3356-a132-e18d8b2d63c4,name=Koke_Cacao,properties={textures=[net.minecraft.util.com.mojang.authlib.properties.Property@46dea383]},legacy=false]
    gamemode=0
    ping=0
    username=Koke_Cacao
    timestamp=1456611222546
  ]

[06:13:42] [Server thread/INFO]: Koke_Cacao[/108.51.44.3:63879] logged in with entity id 0 at ([world] 1629.0, 127.0, 878.0)
[06:13:42] [Server thread/ERROR]: [AuthMe] Unhandled exception occured in onPacketSending(PacketEvent) for AuthMe
java.lang.IllegalStateException: Override onPacketSending to get notifcations of sent packets!
	at com.comphenix.protocol.events.PacketAdapter.onPacketSending(PacketAdapter.java:316) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:638) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:614) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedProtocolInjector.packetQueued(ShadedProtocolInjector.java:312) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedProtocolInjector.onPacketSending(ShadedProtocolInjector.java:278) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector.processSending(ShadedChannelInjector.java:416) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector.access$500(ShadedChannelInjector.java:83) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector$6.handleScheduled(ShadedChannelInjector.java:382) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector$6.onMessageScheduled(ShadedChannelInjector.java:350) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelProxy$2.schedulingRunnable(ShadedChannelProxy.java:127) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedEventLoopProxy.execute(ShadedEventLoopProxy.java:95) [ProtocolLib.jar:?]
	at net.minecraft.server.v1_7_R4.NetworkManager.b(NetworkManager.java:151) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.NetworkManager.handle(NetworkManager.java:129) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerConnection.sendPacket(PlayerConnection.java:803) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerList.tick(PlayerList.java:838) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:738) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1649]
[06:13:42] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo@79e7f9aa[
    action=2
    player=net.minecraft.util.com.mojang.authlib.GameProfile@10452989[id=ea8732b4-041a-3356-a132-e18d8b2d63c4,name=Koke_Cacao,properties={textures=[net.minecraft.util.com.mojang.authlib.properties.Property@46dea383]},legacy=false]
    gamemode=0
    ping=0
    username=Koke_Cacao
    timestamp=1456611222553
  ]

[06:13:44] [Server thread/ERROR]: [AuthMe] Unhandled exception occured in onPacketSending(PacketEvent) for AuthMe
java.lang.IllegalStateException: Override onPacketSending to get notifcations of sent packets!
	at com.comphenix.protocol.events.PacketAdapter.onPacketSending(PacketAdapter.java:316) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:638) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:614) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedProtocolInjector.packetQueued(ShadedProtocolInjector.java:312) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedProtocolInjector.onPacketSending(ShadedProtocolInjector.java:278) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector.processSending(ShadedChannelInjector.java:416) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector.access$500(ShadedChannelInjector.java:83) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector$6.handleScheduled(ShadedChannelInjector.java:382) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector$6.onMessageScheduled(ShadedChannelInjector.java:350) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelProxy$2.schedulingRunnable(ShadedChannelProxy.java:127) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.shaded.ShadedEventLoopProxy.execute(ShadedEventLoopProxy.java:95) [ProtocolLib.jar:?]
	at net.minecraft.server.v1_7_R4.NetworkManager.b(NetworkManager.java:151) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.NetworkManager.handle(NetworkManager.java:129) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerConnection.sendPacket(PlayerConnection.java:803) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerList.tick(PlayerList.java:838) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:738) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1649]
[06:13:44] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo@1b31567a[
    action=2
    player=net.minecraft.util.com.mojang.authlib.GameProfile@10452989[id=ea8732b4-041a-3356-a132-e18d8b2d63c4,name=Koke_Cacao,properties={textures=[net.minecraft.util.com.mojang.authlib.properties.Property@46dea383]},legacy=false]
    gamemode=0
    ping=117
    username=Koke_Cacao
    timestamp=1456611224801
  ]
`

**Comment by ljacqu** [comment]
what /authme version? Pretty sure we fixed this a while ago (a few weeks)

**Comment by sgdc3** [comment]
@KokeCacao What do you mean?

**Comment by KokeCacao** [comment]
I tried -legacy jar, but still error. Then I realize that I am using AuthmeBungeeBridge, maybe I can not change authme version.

**Comment by sgdc3** [comment]
AuthMeBungeeBridge is outdated

**Comment by sgdc3** [comment]
AuthMeBridge have been updated, please open another issue if you have any other issue ;)
