### ISSUE TITLE
Sending the email to the following server failed : smtp.gmail.com:465

### ISSUE THREAD

**Issue by evolfox** [Xephi/AuthMeReloaded#522]
Hello, 

On the latest version AuthMe-5.2-SNAPSHOT-spigot.jar, the mail system is not working. It works on AuthMe - 3.4.

I have this error message :
Failed to send a mail to [*****@outlook.fr]: Sending the email to the following server failed : smtp.gmail.com:465

Thanks

**Comment by ljacqu** [comment]
Can you please download build nr. 787 or upwards and try again? I've improved the logging and we will get more information about the issue.  http://ci.xephi.fr/job/AuthMeReloaded/

In config.yml, under `Security` > `Console`, there is:
```yaml
        # Copy AuthMe log output in a separate file as well?
        logConsole: true
```
Please make sure it is set to `true` as above. Then if you could try to send the email again we will have more detailed information in authme.log. That will be very interesting to see.

**Comment by evolfox** [comment]
The build 787 seems to have failed. Unable to download

**Comment by ljacqu** [comment]
ALternatively, you can use this link https://circleci-tkn.rhcloud.com/api/v1/project/AuthMe-Team/AuthMeReloaded/tree/master/latest/artifacts/AuthMe.jar

**Comment by evolfox** [comment]
ok i have tested with your link and logConsole: true, it's always ditto.

With enableEmailRegistrationSystem: true, i have:

`[02-14 18:40:36]: SQLite driver loaded
[02-14 18:40:36]: SQLite Setup finished
[02-14 18:40:36]: You're using Minecraft 1.6.x or older, Log4J support will be disabled
[02-14 18:40:36]: Hooked correctly with Essentials
[02-14 18:40:36]: Hooked correctly with EssentialsSpawn
[02-14 18:40:36]: AuthMe hooks perfectly with the VeryGames server hosting!
[02-14 18:40:36]: Development builds are available on our jenkins, thanks to f14stelt.
[02-14 18:40:36]: Do you want a good game server? Look at our sponsor GameHosting.it leader in Italy as Game Server Provider!
[02-14 18:40:36]: AuthMe 5.2-SNAPSHOT-bUnknown correctly enabled!
[02-14 18:41:08]: KanekiK registered 192.168.1.16
[02-14 18:41:08]: ERROR: Failed to send a mail to [***@outlook.fr]: [EmailException]: Sending the email to the following server failed : smtp.gmail.com:465
[02-14 18:41:08]: fr.xephi.authme.libs.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465
	at fr.xephi.authme.libs.apache.commons.mail.Email.sendMimeMessage(Email.java:1421)
	at fr.xephi.authme.libs.apache.commons.mail.Email.send(Email.java:1448)
	at fr.xephi.authme.mail.SendMailSSL.sendEmail(SendMailSSL.java:120)
	at fr.xephi.authme.mail.SendMailSSL.access$500(SendMailSSL.java:28)
	at fr.xephi.authme.mail.SendMailSSL$1.run(SendMailSSL.java:66)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: fr.xephi.authme.libs.javax.mail.NoSuchProviderException: smtp
	at fr.xephi.authme.libs.javax.mail.Session.getService(Session.java:806)
	at fr.xephi.authme.libs.javax.mail.Session.getTransport(Session.java:742)
	at fr.xephi.authme.libs.javax.mail.Session.getTransport(Session.java:682)
	at fr.xephi.authme.libs.javax.mail.Session.getTransport(Session.java:662)
	at fr.xephi.authme.libs.javax.mail.Session.getTransport(Session.java:719)
	at fr.xephi.authme.libs.javax.mail.Transport.send0(Transport.java:248)
	at fr.xephi.authme.libs.javax.mail.Transport.send(Transport.java:124)
	at fr.xephi.authme.libs.apache.commons.mail.Email.sendMimeMessage(Email.java:1411)
	... 9 more

[02-14 18:41:23]: ERROR: Failed to send a mail to [***@outlook.fr]: [EmailException]: Sending the email to the following server failed : smtp.gmail.com:465
[02-14 18:41:23]: fr.xephi.authme.libs.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465
	at fr.xephi.authme.libs.apache.commons.mail.Email.sendMimeMessage(Email.java:1421)
	at fr.xephi.authme.libs.apache.commons.mail.Email.send(Email.java:1448)
	at fr.xephi.authme.mail.SendMailSSL.sendEmail(SendMailSSL.java:120)
	at fr.xephi.authme.mail.SendMailSSL.access$500(SendMailSSL.java:28)
	at fr.xephi.authme.mail.SendMailSSL$1.run(SendMailSSL.java:66)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: fr.xephi.authme.libs.javax.mail.NoSuchProviderException: smtp
	at fr.xephi.authme.libs.javax.mail.Session.getService(Session.java:806)
	at fr.xephi.authme.libs.javax.mail.Session.getTransport(Session.java:742)
	at fr.xephi.authme.libs.javax.mail.Session.getTransport(Session.java:682)
	at fr.xephi.authme.libs.javax.mail.Session.getTransport(Session.java:662)
	at fr.xephi.authme.libs.javax.mail.Session.getTransport(Session.java:719)
	at fr.xephi.authme.libs.javax.mail.Transport.send0(Transport.java:248)
	at fr.xephi.authme.libs.javax.mail.Transport.send(Transport.java:124)
	at fr.xephi.authme.libs.apache.commons.mail.Email.sendMimeMessage(Email.java:1411)
	... 9 more

[02-14 18:41:52]: AuthMe 5.2-SNAPSHOT-bUnknown disabled!`

And with enableEmailRegistrationSystem: false, my email is invalide when i type "/email recover mymail@outlook.fr"

**Comment by sgdc3** [comment]
..... Ok we can't shade email libs

**Comment by sgdc3** [comment]
Should have been fixed... Wait for latest build to compile and grab it!

**Comment by evolfox** [comment]
Ok, i have tested with build #7​88 and it's works ! Thank you for your support <3

**Comment by sgdc3** [comment]
@evolfox You're welcome ;)
