### ISSUE TITLE
Duplicate entry ERROR

### ISSUE THREAD

**Issue by smartmadio** [Xephi/AuthMeReloaded#528]
```
[02-14 20:33:34]: ERROR: Error during SQL operation: [MySQLIntegrityConstraintViolationException]: Duplicate entry 'haofan' for key 'username'
[02-14 20:33:34]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'haofan' for key 'username'
	at sun.reflect.GeneratedConstructorAccessor119.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
	at fr.xephi.authme.libs.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at fr.xephi.authme.libs.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at fr.xephi.authme.datasource.MySQL.saveAuth(MySQL.java:353)
	at fr.xephi.authme.datasource.CacheDataSource.saveAuth(CacheDataSource.java:82)
	at fr.xephi.authme.listener.AuthMePlayerListener.onPreLogin(AuthMePlayerListener.java:245)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
	at protocolsupport.protocol.transformer.handlers.PlayerLookupUUID.fireLoginEvents(PlayerLookupUUID.java:97)
	at protocolsupport.protocol.transformer.handlers.PlayerLookupUUID.run(PlayerLookupUUID.java:43)
	at protocolsupport.protocol.transformer.handlers.AbstractLoginListener$3.run(AbstractLoginListener.java:200)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

I've searched whole Authme Database,only one 'haofan' exists.

Spigot 1.8.8 / AuthMeReloaded v5.2-SNAPSHOT (build: 790)

**Comment by ljacqu** [comment]
Thanks for the full error, very helpful. We had another report and I thought it was somewhere else.
Can you tell me what that player was doing? Logging in?, registering?

**Comment by ljacqu** [comment]
saveAuth _inserts_ a record into the db, probably we call it at some wrong place or under wrong circumstances

**Comment by smartmadio** [comment]
He's logging in.

**Comment by DNx5** [comment]
@ljacqu 
https://github.com/AuthMe-Team/AuthMeReloaded/blob/b3734f40102466ef145e5361b6125ed96360ddef/src/main/java/fr/xephi/authme/listener/AuthMePlayerListener.java#L254-L254

**Comment by DNx5** [comment]
@ljacqu 
I just realise, i'm using saveAuth wrong. I thought that was for update PlayerAuth in the database.
But it's not, the method name is ambiguous.

**Comment by DNx5** [comment]
@smartmadio Thanks for useful stacktrace.

**Comment by ljacqu** [comment]
The method name is really bad. I understand the problem with realname now! I was looking at the wrong column I guess

**Comment by DNx5** [comment]
latest development build should work fine.

**Comment by smartmadio** [comment]
Should be fixed,there's no more 'ERROR: Error during SQL operation' message.
