### ISSUE TITLE
Please fix changepassword on dev 793 http://ci.xephi.fr/job/AuthMeReloaded/

### ISSUE THREAD

**Issue by vanthoi** [Xephi/AuthMeReloaded#538]
I use os Linux and Bungee. When command changepassword sussce but it not change pass and consoler error:
[00:37:58 WARN]: [AuthMe] Error while getting country name [AddressNotFoundException]: The address 127.0.0.1 is not in the database.
[00:37:58 WARN]: [AuthMe] Error while getting country name [AddressNotFoundException]: The address 127.0.0.1 is not in the database.
[00:37:58 WARN]: [AuthMe] Error while getting country name [AddressNotFoundException]: The address 127.0.0.1 is not in the database.
[00:37:58 WARN]: [AuthMe] Error while getting country name [AddressNotFoundException]: The address 127.0.0.1 is not in the database.
[00:37:58 WARN]: [AuthMe] Error while getting country name [AddressNotFoundException]: The address 127.0.0.1 is not in the database.

**Comment by sgdc3** [comment]
Issue with GeoIp2

**Comment by vanthoi** [comment]
I discovered one more thing. That is the new version of your overloaded error linux kernel. It makes the whole system unresponsive. I upgraded to the most recent version I had trouble continuous server crash but it is not itself off debts due to nostalgic without any further feedback. I could not find fault in crash by one the number of times I have read a text file but by chunk, clearlag plugin. I was forced to reset the new server. After creating my back has not escaped the incident on each plugin I have searched and have discovered authme reload the recent update breaking something. Although I have tried to improve on the time tick 120000 max it still happens. And hung there until I reboot my server system! return to the previous version, then run normally.
 Wish you fix errors on the thank! I

**Comment by DNx5** [comment]
could you test this version?
http://ci.xephi.fr/job/AuthMeReloaded/797/artifact/target/AuthMe-5.2-SNAPSHOT-spigot.jar
also, it would be helpful if you give us error/crash log or timings report.

**Comment by vanthoi** [comment]
No I user Bukkit 1.8.3. OS linux CentOS. OK I will build new server add add plugin test timming!

**Comment by sgdc3** [comment]
Can you post your timings? /timings on
then login and quit more times
after 5 minutes /timings paste and post here the link that appears in chat

**Comment by vanthoi** [comment]
ok it is not crash by plugin. it crash by RAM server have 1 chanel error. Thanks

**Comment by sgdc3** [comment]
Ok open another report if you find other issues ;) Thank you!

**Comment by vanthoi** [comment]
I use Spigot server: This Spigot build supports Minecraft clients both of versions 1.7.x and of 1.8.x.
I test all ver dev: error!

 [19:20:48 INFO]: [AuthMe] Enabling AuthMe v5.2-SNAPSHOT-b823
[19:20:48 INFO]: [AuthMe] Detected deprecated property settings.delayJoinLeaveMessages
[19:20:48 INFO]: [AuthMe] Note that we now also have the settings settings.removeJoinMessage and settings.removeLeaveMessage
[19:20:48 INFO]: [AuthMe] Renamed settings.delayJoinLeaveMessages to settings.delayJoinMessage
[19:20:48 INFO]: [AuthMe] Merged new config options
[19:20:48 INFO]: [AuthMe] Please check your config.yml file for new settings!
[19:20:48 INFO]: [AuthMe] SQLite driver loaded
[19:20:48 INFO]: [AuthMe] SQLite Setup finished
[19:20:48 ERROR]: Error occurred while enabling AuthMe v5.2-SNAPSHOT-b823 (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.build(Lcom/google/common/cache/CacheLoader;)Lcom/google/common/cache/LoadingCache;
	at fr.xephi.authme.datasource.CacheDataSource.<init>(CacheDataSource.java:42) ~[?:?]
	at fr.xephi.authme.AuthMe.setupDatabase(AuthMe.java:545) ~[?:?]
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:243) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot-1.7.10.jar:git-Spigot-1649]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot-1.7.10.jar:git-Spigot-1649]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.7.10.jar:git-Spigot-1649]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot-1.7.10.jar:git-Spigot-1649]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot-1.7.10.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [spigot-1.7.10.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [spigot-1.7.10.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [spigot-1.7.10.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.7.10.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot-1.7.10.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10.jar:git-Spigot-1649]

Ver not error : dev create: 16/12/2015 bug it is send mail recovery error : not pass and user!
It is will send mail to mail!

because you have  ver dev ? support on ver server spigot server 1.7.10 support 1.7.x->1.8.x ?

Thanks!

**Comment by games647** [comment]
Try to use the legacy version.

**Comment by vanthoi** [comment]
Thank it is worked!
