### ISSUE TITLE
AuthMeBridge v1.5 error (AuthMe-5.2-SNAPSHOT-spigot b813)

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#557]
[17:42:08] [Craft Scheduler Thread - 0/INFO]: [AuthMe] TNTZoli2003 logged in!
[17:42:08] [Server thread/ERROR]: Could not pass event LoginEvent to AuthMeBridge v1.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot_1.8.jar:git-PaperSpigot-ee63dbe]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[spigot_1.8.jar:git-PaperSpigot-ee63dbe]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.8.jar:git-PaperSpigot-ee63dbe]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [spigot_1.8.jar:git-PaperSpigot-ee63dbe]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [spigot_1.8.jar:git-PaperSpigot-ee63dbe]
	at fr.xephi.authme.process.login.ProcessSyncPlayerLogin.run(ProcessSyncPlayerLogin.java:183) [AuthMe-5.2-SNAPSHOT-spigot.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [spigot_1.8.jar:git-PaperSpigot-ee63dbe]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [spigot_1.8.jar:git-PaperSpigot-ee63dbe]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:781) [spigot_1.8.jar:git-PaperSpigot-ee63dbe]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot_1.8.jar:git-PaperSpigot-ee63dbe]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot_1.8.jar:git-PaperSpigot-ee63dbe]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot_1.8.jar:git-PaperSpigot-ee63dbe]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
Caused by: java.lang.NoSuchMethodError: fr.xephi.authme.events.LoginEvent.isLogin()Z
	at com.crylegend.authmebridge.AuthMeBridgeListener.onAuthMeLogin(AuthMeBridgeListener.java:24) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[spigot_1.8.jar:git-PaperSpigot-ee63dbe]
	... 12 more

**Comment by games647** [comment]
>NoSuchMethodError: fr.xephi.authme.events.LoginEvent.isLogin()Z
at com.crylegend.authmebridge.AuthMeBridgeListener.onAuthMeLogin(AuthMeBridgeListener.java:24)

This is error comes from AuthMe bridge.

**Comment by sgdc3** [comment]
AuthMeBridge is no longer supported.

**Comment by andris155** [comment]
:'(

**Comment by sgdc3** [comment]
We'll try to fix our AuthMeBungee xD

**Comment by andris155** [comment]
:+1:

**Comment by beetle2k** [comment]
the method isLogin() has no longer avaiable on LoginEvent class.
I fixed it on my server, i'm developer and i will post this fix here:

Old code:

>     @EventHandler
>     public void onAuthMeLogin(LoginEvent event) {
>         if (!event.isLogin()) {
>             return;
>         }
>         playerLogin(event.getPlayer());
>     }

New code:
```
    @EventHandler
    public void onAuthMeLogin(LoginEvent event) {
        // Event fired when a player has successfully logged in or registered. Removed isLogin();
        // Now check ifs return a player
        // getPlayer(): Return the player that has successfully logged in or registered.
        if (event.getPlayer() == null) {
            return;
        }
        playerLogin(event.getPlayer());
    }
```

Tested on AuthMe 5.2

Jar is on attachment


[AuthMeBridgeBukkit-Fixed isLogin.zip](https://github.com/Xephi/AuthMeReloaded/files/158939/AuthMeBridgeBukkit-Fixed.isLogin.zip)

**Comment by andris155** [comment]
Thanks! Work!

**Comment by CryLegend** [comment]
Updated, now on github: https://github.com/CryLegend/AuthMeBridge

**Comment by sgdc3** [comment]
@CryLegend Hello! Thanks ;)
