### ISSUE TITLE
Spigot 1.9: Exception in thead

### ISSUE THREAD

**Issue by ireeskenz** [Xephi/AuthMeReloaded#579]
I go an error while Authme is booting "Exception in thread "Craft Scheduler Thread - 7", can you help me?

**Comment by games647** [comment]
Could you post the stack trace?

**Comment by ireeskenz** [comment]
`[11:02:46] [Craft Scheduler Thread - 7/WARN]: Exception in thread "Craft Scheduler Thread - 7" 
[11:02:46] [Craft Scheduler Thread - 7/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing task 35
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at fr.xephi.authme.Metrics.postPlugin(Metrics.java:335)
	at fr.xephi.authme.Metrics.access$400(Metrics.java:57)
	at fr.xephi.authme.Metrics$1.run(Metrics.java:223)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more`

**Comment by games647** [comment]
>NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()

Try to update to the newest dev build

**Comment by sgdc3** [comment]
Please update and then open another issue ;)
