### ISSUE TITLE
Authme Reloaded Error : Out of Memory

### ISSUE THREAD

**Issue by TheIntelloBox** [Xephi/AuthMeReloaded#596]
Hello all ! :D

I have an error with Authme :+1: 

`[01:10:18] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to AuthMe v5.0-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.7.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.7.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.7.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.7.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerList.attemptLogin(PlayerList.java:456) [spigot-1.8.7.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:118) [spigot-1.8.7.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot-1.8.7.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot-1.8.7.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot-1.8.7.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot-1.8.7.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.7.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.7.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.7.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method) ~[?:1.8.0_72]
	at java.lang.Thread.start(Thread.java:714) ~[?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950) ~[?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357) ~[?:1.8.0_72]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[?:1.8.0_72]
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:681) ~[?:1.8.0_72]
	at fr.xephi.authme.datasource.DatabaseCalls.isAuthAvailable(DatabaseCalls.java:23) ~[?:?]
	at fr.xephi.authme.listener.AuthMePlayerListener.onPlayerLogin(AuthMePlayerListener.java:404) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor441.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.7.jar:git-Spigot-db6de12-18fbb24]
	... 13 more`

**Comment by sgdc3** [comment]
You need to update authme to latest dev build. Get it at http://ci.xephi.fr/job/AuthMeReloaded
