### ISSUE TITLE
Whats wrong?

### ISSUE THREAD

**Issue by MrMurfy** [Xephi/AuthMeReloaded#607]
`[20:12:43] [Craft Scheduler Thread - 4/WARN]: Exception in thread "Craft Scheduler Thread - 4" 
[20:12:43] [Craft Scheduler Thread - 4/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing task 37
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at fr.xephi.authme.Metrics.postPlugin(Metrics.java:335)
	at fr.xephi.authme.Metrics.access$400(Metrics.java:57)
	at fr.xephi.authme.Metrics$1.run(Metrics.java:223)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more`

**Comment by sgdc3** [comment]
Update your version to 5.2: http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-spigot.jar
