### ISSUE TITLE
Error Craft Scheduler Thread - 644

### ISSUE THREAD

**Issue by DardBrinza** [Xephi/AuthMeReloaded#636]
Latest #912
```
[09:13:01 WARN]: Exception in thread "Craft Scheduler Thread - 644"
[09:13:01 WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.2-SNAPSHOT-b905 generated an exception while executing task 1483584
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
        at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:405)
        at ru.tehkode.permissions.bukkit.PermissionsEx.getUser(PermissionsEx.java:416)
        at fr.xephi.authme.permission.PermissionsManager.hasPermission(PermissionsManager.java:369)
        at fr.xephi.authme.permission.PermissionsManager.hasPermission(PermissionsManager.java:313)
        at fr.xephi.authme.permission.PermissionsManager.hasPermission(PermissionsManager.java:304)
        at fr.xephi.authme.process.join.AsynchronousJoin.run(AsynchronousJoin.java:80)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by ljacqu** [comment]
Are you using PermissionsEx? Which version?

In the logs, does it look like PermissionsEx was disabled? Or does AuthMe say it hooked into PermissionsEx before it was enabled?

**Comment by DardBrinza** [comment]
Pex version 1.23.3
EnablePermissionCheck: false

**Comment by DardBrinza** [comment]
Logs:
```
[09:12:58] [Server thread/INFO]: Stopping the server
[09:12:58] [Server thread/INFO]: Stopping server
[09:12:58] [Server thread/INFO]: [AuthMe] Disabling AuthMe v5.2-SNAPSHOT-b905
[09:12:58] [Server thread/INFO]: [AuthMe] AuthMe 5.2-SNAPSHOT-b905 disabled!
[09:12:58] [AuthMe-DataSource#close/INFO]: [AuthMe] Waiting for 4 tasks to finish
[09:12:58] [AuthMe-DataSource#close/INFO]: [AuthMe] Progress: 1 / 4
[09:12:58] [AuthMe-DataSource#close/INFO]: [AuthMe] Progress: 2 / 4
[09:12:58] [Server thread/INFO]: [PermissionsEx] Disabling PermissionsEx v1.23.3
[09:12:58] [Server thread/INFO]: WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
[09:12:58] [Server thread/INFO]: Permissions listed in as player-commands will be given to all users.
------------------------------------------
my other plugin disabled...
------------------------------------------
[09:12:58] [Server thread/INFO]: Saving players
[09:12:58] [Server thread/INFO]: Saving worlds
[09:12:58] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[09:13:01] [Craft Scheduler Thread - 644/WARN]: Exception in thread "Craft Scheduler Thread - 644" 
[09:13:01] [Craft Scheduler Thread - 644/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.2-SNAPSHOT-b905 generated an exception while executing task 1483584
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
	at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:405)
	at ru.tehkode.permissions.bukkit.PermissionsEx.getUser(PermissionsEx.java:416)
	at fr.xephi.authme.permission.PermissionsManager.hasPermission(PermissionsManager.java:369)
	at fr.xephi.authme.permission.PermissionsManager.hasPermission(PermissionsManager.java:313)
	at fr.xephi.authme.permission.PermissionsManager.hasPermission(PermissionsManager.java:304)
	at fr.xephi.authme.process.join.AsynchronousJoin.run(AsynchronousJoin.java:80)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[09:13:01] [Server thread/INFO]: Saving chunks for level 'world_nether'/Nether

```

**Comment by sgdc3** [comment]
Does this happen everytime or only once?

**Comment by sgdc3** [comment]
It may be caused by a player trying to join the server while it's shutting down.

**Comment by DardBrinza** [comment]
only once

**Comment by sgdc3** [comment]
Ok, not a big issue but i think we can avoid it ;)

**Comment by sgdc3** [comment]
Old issue, probably fixed since months, closing.

**Comment by ljacqu** [comment]
I agree to closing – but just to explain the background: the issue is when AuthMe is disabling, we wait on certain tasks to complete, during which the permission plugin we hooked in disabled. It's a little surprising that we wouldn't unhook from it in the process, but it may have been some rare condition...

**Comment by sgdc3** [comment]
@ljacqu we also changed lots of stuff
