### ISSUE TITLE
Authme register bug (with wordpress)

### ISSUE THREAD

**Issue by hakumanatatu** [Xephi/AuthMeReloaded#638]
Hi,
i'm update my server to 1.9.2. Download latest version of authme "#919 (5.4.2016 23:55:02)". (same bug with version from dev.bukkit)
Spigot version: 1.9.2
It is a problem with the wordpress table usermeta and SQL insert command.
`[04-06 14:29:36]: ERROR: Error during SQL operation: [BatchUpdateException]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(1,'last_name',''),(1,'nickname','hakumanatatu'),(1,'description',''),(1,'rich_e' at line 1
[04-06 14:29:36]: java.sql.BatchUpdateException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(1,'last_name',''),(1,'nickname','hakumanatatu'),(1,'description',''),(1,'rich_e' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1160)
	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1582)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1248)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:959)
	at fr.xephi.authme.libs.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at fr.xephi.authme.libs.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at fr.xephi.authme.datasource.MySQL.saveAuth(MySQL.java:496)
	at fr.xephi.authme.datasource.CacheDataSource.saveAuth(CacheDataSource.java:95)
	at fr.xephi.authme.process.register.AsyncRegister.passwordRegister(AsyncRegister.java:146)
	at fr.xephi.authme.process.register.AsyncRegister.run(AsyncRegister.java:97)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`
Can you fix it please ? Thanks

**Comment by falget** [comment]
Hi, i have the same error, use last dev builds 930. I hope you fix it.

**Comment by falget** [comment]
Please fix it

**Comment by sgdc3** [comment]
Should have been fixed since build 933 ;)

**Comment by falget** [comment]
No nothing has changed, the same error. Use 935 build.

**Comment by ljacqu** [comment]
Thanks for the feedback.

@falget -- what's your `wordpressTablePrefix` and `mySQLTablename` set to? 

Looks like we're doing something wrong with the following code (saveAuth:432).
```java
"INSERT INTO " + wordpressPrefix + "usermeta (user_id, meta_key, meta_value) VALUES (?,?,?);"
```

**Comment by falget** [comment]
wordpressTablePrefix: 'wp_'
mySQLTablename: 'wp_users'
When user register he added to the table 'wp_users' but not in the table 'wp_usermeta'

**Comment by falget** [comment]
@ljacqu Can you debug plugin and see what result sql query after pst2.addBatch(); code ?

**Comment by ljacqu** [comment]
Aww man this was probably the worst bug ever, I just had to remove an ending `;`. Please let me know if this solves the issue for you. It did for me on a test DB. Thanks for your patience. @falget

**Comment by falget** [comment]
So this helped, thank you. :)
