### ISSUE TITLE
CONSOLE ERROR

### ISSUE THREAD

**Issue by RAZERMC** [Xephi/AuthMeReloaded#643]
USING SPIGOT 1.8.8 
AUTHME BUILD#923
JAVA VERSION 8

[00:14:34] [Server thread/WARN]: [AuthMe] Task #23 for AuthMe v5.2-SNAPSHOT-b923 generated an exception
java.lang.NoClassDefFoundError: com/comphenix/protocol/reflect/MethodUtils
	at fr.xephi.authme.process.join.AsynchronousJoin.<init>(AsynchronousJoin.java:49) ~[?:?]
	at fr.xephi.authme.process.Management.performJoin(Management.java:52) ~[?:?]
	at fr.xephi.authme.listener.AuthMePlayerListener$2.run(AuthMePlayerListener.java:242) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot188.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot188.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot188.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot188.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot188.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot188.jar:git-Spigot-5f38d38-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]

**Comment by sgdc3** [comment]
Update your protocollib version

**Comment by RAZERMC** [comment]
thanks

**Comment by ljacqu** [comment]
What if a server doesn't want to use it? Just tried with a plain server and AuthMe, this error will occur

**Comment by RAZERMC** [comment]
im fine with protocol lib even my anti cheat uses protocol lib EVEN NOCHEATPLUS uses protocol lib so yeah 50% or more servers uses protocol lib XD

**Comment by games647** [comment]
Yes but @ljacqu is right. It should be only used in the ProtocolLib listeners, because we know it's available there.

**Comment by sgdc3** [comment]
Ok fixed ;)

**Comment by RAZERMC** [comment]
ok testing it again after downloading the resource #924

**Comment by RAZERMC** [comment]
no console error now thanks

**Comment by sgdc3** [comment]
;)
