### ISSUE TITLE
NULL POINTER EXCEPTION LimitedCreative 

### ISSUE THREAD

**Issue by RAZERMC** [Xephi/AuthMeReloaded#644]
USING SPIGOT 1.8.8
AUTHME BUILD #924
JAVA VERSION 8

[12:43:42] [Craft Scheduler Thread - 3/INFO]: [AuthMe] AutoPurge: Removed 0 .dat Files
[12:43:42] [Craft Scheduler Thread - 3/WARN]: Exception in thread "Craft Scheduler Thread - 3" 
[12:43:42] [Craft Scheduler Thread - 3/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.2-SNAPSHOT-b924 generated an exception while executing task 428
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at fr.xephi.authme.DataManager.purgeLimitedCreative(DataManager.java:66)
	at fr.xephi.authme.AuthMe$4.run(AuthMe.java:739)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)

**Comment by RAZERMC** [comment]
I am not using the LimitedCreative Plugin

**Comment by RAZERMC** [comment]
How to reproduce the error:

previously using authme 3.5 
removed the authme 3.5 plugin but not the files as to convert the 3.5 database  to sql format
installed the authme 5.2 build 924 to the plugins folder 
started the server
authme converted the old database to sql
(my previous setting was to auto purge accounts essentials dat files and limitedcreative but i am not using limited creative at the moment i used it a week ago but removed it)
authme initiate purge 
console error appears

**Comment by sgdc3** [comment]
Fixed
