### ISSUE TITLE
/authme switchantibot error

### ISSUE THREAD

**Issue by tuanjr** [Xephi/AuthMeReloaded#667]
`[15:03:19] [Server thread/WARN]: Unexpected exception while parsing console command "authme switchantibot"
org.bukkit.command.CommandException: Unhandled exception executing command 'authme' in plugin AuthMe v5.2-SNAPSHOT-b945
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.2.jar:git-Paper-665]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.9.2.jar:git-Paper-665]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) ~[patched_1.9.2.jar:git-Paper-665]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchServerCommand(CraftServer.java:627) [patched_1.9.2.jar:git-Paper-665]
	at net.minecraft.server.v1_9_R1.DedicatedServer.aL(DedicatedServer.java:442) [patched_1.9.2.jar:git-Paper-665]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:405) [patched_1.9.2.jar:git-Paper-665]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:721) [patched_1.9.2.jar:git-Paper-665]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:620) [patched_1.9.2.jar:git-Paper-665]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.NullPointerException
	at fr.xephi.authme.command.executable.authme.SwitchAntiBotCommand.executeCommand(SwitchAntiBotCommand.java:23) ~[?:?]
	at fr.xephi.authme.command.CommandHandler.executeCommand(CommandHandler.java:87) ~[?:?]
	at fr.xephi.authme.command.CommandHandler.handleCommandResult(CommandHandler.java:59) ~[?:?]
	at fr.xephi.authme.command.CommandHandler.processCommand(CommandHandler.java:52) ~[?:?]
	at fr.xephi.authme.AuthMe.onCommand(AuthMe.java:823) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.9.2.jar:git-Paper-665]
	... 8 more`

**Comment by ljacqu** [comment]
Thanks for the bug report—this should be fixed now.

We need to improve our way of initializing services --> #432 because the current way is prone to bugs such as this one.
