### ISSUE TITLE
An error in the console when sending emails

### ISSUE THREAD

**Issue by jeka94** [Xephi/AuthMeReloaded#678]
`[16:17:50] [Server thread/INFO]: [AuthMe] jeka94 registered 127.0.0.1
[16:17:50] [Craft Scheduler Thread - 2/WARN]: Exception in thread "Craft Scheduler Thread - 2" 
[16:17:50] [Craft Scheduler Thread - 2/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing task 372
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/sun/mail/util/MailLogger
	at javax.mail.Session.initLogger(Session.java:226)
	at javax.mail.Session.<init>(Session.java:210)
	at javax.mail.Session.getInstance(Session.java:247)
	at fr.xephi.authme.SendMailSSL$1.run(SendMailSSL.java:66)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.sun.mail.util.MailLogger
	at java.net.URLClassLoader.findClass(Unknown Source)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 9 more
`

**Comment by sgdc3** [comment]
Please, update to latest dev build available at http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-spigot.jar
