### ISSUE TITLE
Error on 1.8.9 Using Java 8 (MAYBE) !

### ISSUE THREAD

**Issue by TheIntelloBox** [Xephi/AuthMeReloaded#714]
[12:29:39] [Head Conversion Thread - 0/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@823a805[id=fc667a43-abb6-424f-90f6-8a1295bb473f,name=TheIntelloBox,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.TileEntitySkull$1.load(TileEntitySkull.java:70) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.TileEntitySkull$1.load(TileEntitySkull.java:1) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.TileEntitySkull$3.run(TileEntitySkull.java:172) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by games647** [comment]
https://github.com/PaperMC/Paper/issues/128
