### ISSUE TITLE
"Force Spawn Location On Join" won't work on new build!

### ISSUE THREAD

**Issue by tuanjr** [Xephi/AuthMeReloaded#729]
in the past, When i use build 1004:
with setting like this: spawnPriority: 'essentials,authme,multiverse,default'
player always spawn on "Essentials's spawn" when join

But now, on Build 1053, player always spawn on "quit location"

> 
        ForceSingleSession: true
        ForceSpawnLocOnJoin: 
            # If enabled, every player will be teleported to the world spawnpoint
            # after successful authentication.
            # The quit location of the player will be overwritten.
            # This is different from "teleportUnAuthedToSpawn" that teleport player
            # back to his quit location after the authentication.
            enabled: true
            # WorldNames where we need to force the spawn location
            # Case-sensitive!
            worlds: 
            - 'hub'
        # This option will save the quit location of the players.
        SaveQuitLocation: false
        # To activate the restricted user feature you need
        # to enable this option and configure the AllowedRestrictedUser field.
        AllowRestrictedUser: false
        # The restricted user feature will kick players listed below
        # if they don't match the defined IP address.
        # Example:
        #     AllowedRestrictedUser:
        #     - playername;127.0.0.1
        AllowedRestrictedUser: 
        - 'playername;127.0.0.1'
        # Should unregistered players be kicked immediately?
        kickNonRegistered: false
        # Should players be kicked on wrong password?
        kickOnWrongPassword: true
        # Should not logged in players be teleported to the spawn?
        # After the authentication they will be teleported back to
        # their normal position.
        teleportUnAuthedToSpawn: true
        # Can unregistered players walk around?
        allowMovement: false
        # Should not authenticated players have speed = 0?
        # This will reset the fly/walk speed to default value after the login.
        removeSpeed: true
        # After how many seconds should players who fail to login or register
        # be kicked? Set to 0 to disable.
        timeout: 60
        # Regex syntax of allowed characters in the player name.
        allowedNicknameCharacters: '[a-zA-Z0-9_]*'
        # How far can unregistered players walk?
        # Set to 0 for unlimited radius
        allowedMovementRadius: 5
        # Enable double check of password when you register
        # when it's true, registration requires that kind of command:
        # /register <password> <confirmPassword>
        enablePasswordConfirmation: true
        # Should we protect the player inventory before logging in? Requires ProtocolLib.
        ProtectInventoryBeforeLogIn: true
        # Should we deny the tabcomplete feature before logging in? Requires ProtocolLib.
        DenyTabCompleteBeforeLogin: true
        # Should we hide the tablist before logging in? Requires ProtocolLib.
        HideTablistBeforeLogin: false
        # Should we display all other accounts from a player when he joins?
        # permission: /authme.admin.accounts
        displayOtherAccounts: false
        # Ban ip when the ip is not the ip registered in database
        banUnsafedIP: false
        # Spawn priority; values: authme, essentials, multiverse, default
        spawnPriority: 'essentials,authme,multiverse,default'
        # Maximum Login authorized by IP
>

**Comment by rErEaT** [comment]
confirm ! its bad noew!

**Comment by ljacqu** [comment]
@tuanjr @rErEaT May I ask you to verify with build n. 1110 or above? http://ci.xephi.fr/job/AuthMeReloaded/
I tested on Spigot 1.8.8 various priorities and the force spawn location feature and it seemed to work.

**Comment by tuanjr** [comment]
Just install AuthMe-5.2-SNAPSHOT-legacy-1111.jar and tested, everythings fine, work. ( PaperSpigot 1.9.2)

**Comment by ljacqu** [comment]
That's excellent news, @tuanjr. Thanks for the bug report and for the prompt answer! 

I'm not closing this yet because I just noticed I need to fix the /logout behavior a little.

**Comment by rErEaT** [comment]
[22:23:22] [User Authenticator #3/INFO]: UUID of player happyseed01 is ecfb0268-c5e2-3cb5-bf19-df49548bfc2e
[22:23:22] [Server thread/INFO]: [Essentials] Found new UUID for happyseed01. Replacing 19777db2-bc92-34a4-b4ee-d98dfb27df56 with ecfb0268-c5e2-3cb5-bf19-df49548bfc2e
[22:23:23] [Server thread/INFO]: happyseed01[/84.0.167.108:51797] logged in with entity id 9915 at ([world]1846.5, 140.0, -460.5)
[22:23:23] [pool-14-thread-1/INFO]: Creating empty config: /home/minecraft/multicraft/servers/server3/plugins/Essentials/userdata/ecfb0268-c5e2-3cb5-bf19-df49548bfc2e.yml
[22:23:23] [Server thread/WARN]: [AuthMe] Task #70078 for AuthMe v5.2-SNAPSHOT-b1116 generated an exception
java.lang.IllegalStateException: FirstSpawnTeleportEvent cannot be triggered asynchronously from primary server thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at fr.xephi.authme.util.BukkitService.callEvent(BukkitService.java:180) ~[?:?]
	at fr.xephi.authme.util.TeleportationService$1.run(TeleportationService.java:135) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by ljacqu** [comment]
@rErEaT Sorry about that, I will have to fix it tomorrow as it's getting quite late.

**Comment by rErEaT** [comment]
okay :)

**Comment by ljacqu** [comment]
Should be fixed now, @rErEaT. One last thing before closing this—looks like first spawn handling doesn't work as expected.
