### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by qubeee** [Xephi/AuthMeReloaded#752]
Hi, I got this error message in console. I tried to use different AuthMe versions but it didn't help.

>[10:19:17] [Craft Scheduler Thread - 287/WARN]: Exception in thread "Craft Scheduler Thread - 287" 
[10:19:17] [Craft Scheduler Thread - 287/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing task 41
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at fr.xephi.authme.Metrics.postPlugin(Metrics.java:335)
	at fr.xephi.authme.Metrics.access$400(Metrics.java:57)
	at fr.xephi.authme.Metrics$1.run(Metrics.java:223)
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by qubeee** [comment]
And there is a bug or something. When players join the server, their "skin" remain to stand at spawn as an entity so it is almost impossible to move when you teleport to spawn. I don't really know if it is a AuthMe's problem

**Comment by Platinteufel** [comment]
Do you use SkinsRestorer?

**Comment by qubeee** [comment]
Yes I do. Is there any way to fix it?

**Comment by Platinteufel** [comment]
For 1.9.4 there is no stable version of SkinsRestorer yet, it's quite buggy at the moment (ghost skins, skins don't show, ...)

**Comment by Platinteufel** [comment]
But please update to the latest AuthMe beta build and look if this error is still in console.
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/files/78-auth-me-5-2-beta-2/

**Comment by sgdc3** [comment]
5.0 is incompatible with 1.9
