### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by juanruiz85** [Xephi/AuthMeReloaded#754]
The console is showing this error sometimes

[16:12:43] [Craft Scheduler Thread - 3/WARN]: Exception in thread "Craft Scheduler Thread - 3"
[16:12:43] [Craft Scheduler Thread - 3/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing task 16
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
at fr.xephi.authme.Metrics.postPlugin(Metrics.java:335)
at fr.xephi.authme.Metrics.access$400(Metrics.java:57)
at fr.xephi.authme.Metrics$1.run(Metrics.java:223)
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

**Comment by rErEaT** [comment]
http://ci.xephi.fr/job/AuthMeReloaded/
