### ISSUE TITLE
Authme Error

### ISSUE THREAD

**Issue by EendyGame** [Xephi/AuthMeReloaded#756]
`[15:22:16 WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing task 314 
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
at java.lang.Thread.run(Thread.java:745) 
Caused by: java.lang.IllegalStateException: Asynchronous player kick! 
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) 
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:214) 
at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:90) 
at fr.xephi.authme.process.Management$5.run(Management.java:81) 
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) 
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) 
... 3 more`

`Exception in thread "Craft Scheduler Thread - 2" 
[15:08:11 WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing task 48
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Asynchronous player kick!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:214)
at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:90)
at fr.xephi.authme.process.Management$5.run(Management.java:81)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more`

**Comment by ljacqu** [comment]
> AuthMe v5.0-SNAPSHOT 

please upgrade
http://ci.xephi.fr/job/AuthMeReloaded/
