### ISSUE TITLE
I am using "KCauldron" Server, but the plugin does not support.

### ISSUE THREAD

**Issue by authme** [Xephi/AuthMeReloaded#77]
Although the server can be loaded normally, but all commands are unusable.

KCauldron is an updated version of Cauldron server, corresponding to the client version 1.7.10.

KCauldron's Web Site: https://gitlab.prok.pw/Prototik/KCauldron

The KCauldron supports only 3.5 version of the plugin, but it's 5.0 now...

The plugin can consider supporting it?

Thank you very much!

**Comment by Trojaner25** [comment]
Its a KCauldron issue, not an Authme issue.

**Comment by sgdc3** [comment]
@Trojaner25 How do you know that? AuthMe should be compatible with all 1.7.10 servers, also KCauldron. If there are compatibility issues with non craftbukkit/spigot implementations this is a problem!

**Comment by authme** [comment]
Trojaner25, "Its a KCauldron issue, not an Authme issue.", your mean's the Server supported Plugin but Plugin not to supported the Server? What...Are you kindding me?...

**Comment by Trojaner25** [comment]
@authme No, the plugin supports the server but not the server the plugin.

@sgdc3 Authme supports the latest vanilla craftbukkit 1.7.10 servers, even if not, this commit: https://github.com/Xephi/AuthMeReloaded/commit/4e75fb76d0cc8b971922c3ce206469df7a7d2567 should have fixed it.

**Comment by authme** [comment]
Thanks, I try again, I think I should be overlooked something.

**Comment by Trojaner25** [comment]
However, do you have any exceptions or something? Any "Warnings" or "Severe" errors in console?

**Comment by authme** [comment]
...No, I can't find any Warnings Or ERROR, but Is not worked.

**Comment by Xephi** [comment]
Can I have your starting logs? (paste them on pastebin/whatever else)

**Comment by authme** [comment]
Please wait, I find the log.

**Comment by authme** [comment]
[19:35:19] [Server thread/WARN]: =============================================================
[19:35:19] [Server thread/INFO]: [AuthMe] Loading AuthMe v${version}
[19:35:19] [Server thread/INFO]: KCauldron: Patching org.bukkit.craftbukkit.v1_7_R4.CraftWorld for compatibility with Mystcraft
[19:35:20] [Server thread/INFO]: KCauldron: Patching ms for compatibility with Mystcraft
[19:35:20] [Server thread/INFO]: Loading dimension 0 (world) (net.minecraft.server.dedicated.DedicatedServer@27330551)
[19:35:20] [Server thread/INFO]: Loading dimension 1 (DIM1) (net.minecraft.server.dedicated.DedicatedServer@27330551)
[19:35:20] [Server thread/INFO]: Loading dimension -1 (DIM-1) (net.minecraft.server.dedicated.DedicatedServer@27330551)
[19:35:20] [Server thread/INFO]: Preparing start region for level 0
[19:35:20] [Server thread/INFO]: KCauldron: Patching net.minecraftforge.common.chunkio.ChunkIOProvider for compatibility with Mystcraft
[19:35:21] [Server thread/INFO]: [AuthMe] Enabling AuthMe v${version}
[19:35:21] [Server thread/INFO]: [AuthMe] Loading Configuration File...
[19:35:21] [Server thread/INFO]: [AuthMe] Set Language: en
[19:35:21] [Server thread/ERROR]: Error occurred while enabling AuthMe v${version} (Is it up to date?)
java.lang.NoClassDefFoundError: net/milkbowl/vault/permission/Permission
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.7.0_80]
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.7.0_80]
	at java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:1.7.0_80]
	at java.lang.Thread$1.run(Unknown Source) ~[?:1.7.0_80]
	at java.lang.Thread$1.run(Unknown Source) ~[?:1.7.0_80]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_80]
	at java.lang.Thread.auditSubclass(Unknown Source) ~[?:1.7.0_80]
	at java.lang.Thread.isCCLOverridden(Unknown Source) ~[?:1.7.0_80]
	at java.lang.Thread.init(Unknown Source) ~[?:1.7.0_80]
	at java.lang.Thread.init(Unknown Source) ~[?:1.7.0_80]
	at java.lang.Thread.<init>(Unknown Source) ~[?:1.7.0_80]
	at fr.xephi.authme.DataManager.<init>(DataManager.java:20) ~[?:?]
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:241) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
[19:35:21] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[19:35:21] [Server thread/INFO]: Done (4.127s)! For help, type "help" or "?"
[19:35:21] [Server thread/INFO]: Registered command forge with permission node net.minecraftforge.server.command.ForgeCommand
[19:35:26] [KCauldron version retrievier/WARN]: Error occured during retriving version
java.lang.Throwable
	at kcauldron.KLog.log(KLog.java:30) [KLog.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at kcauldron.KLog.warning(KLog.java:41) [KLog.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at kcauldron.updater.KVersionRetriever.uncaughtException(KVersionRetriever.java:102) [KVersionRetriever.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at kcauldron.updater.KVersionRetriever.check(KVersionRetriever.java:96) [KVersionRetriever.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at kcauldron.updater.KVersionRetriever.run(KVersionRetriever.java:59) [KVersionRetriever.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.Handshaker.processLoop(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.Handshaker.process_record(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.7.0_80]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394) ~[SSLConnectionSocketFactory.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353) ~[SSLConnectionSocketFactory.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) ~[DefaultHttpClientConnectionOperator.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[PoolingHttpClientConnectionManager.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[MainClientExec.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[MainClientExec.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[ProtocolExec.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[RetryExec.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[RedirectExec.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[InternalHttpClient.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[CloseableHttpClient.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[CloseableHttpClient.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at kcauldron.updater.KVersionRetriever.check(KVersionRetriever.java:80) ~[KVersionRetriever.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	... 2 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source) ~[?:1.7.0_80]
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source) ~[?:1.7.0_80]
	at sun.security.validator.Validator.validate(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.Handshaker.processLoop(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.Handshaker.process_record(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.7.0_80]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394) ~[SSLConnectionSocketFactory.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353) ~[SSLConnectionSocketFactory.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) ~[DefaultHttpClientConnectionOperator.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[PoolingHttpClientConnectionManager.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[MainClientExec.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[MainClientExec.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[ProtocolExec.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[RetryExec.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[RedirectExec.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[InternalHttpClient.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[CloseableHttpClient.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[CloseableHttpClient.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at kcauldron.updater.KVersionRetriever.check(KVersionRetriever.java:80) ~[KVersionRetriever.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	... 2 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source) ~[?:1.7.0_80]
	at java.security.cert.CertPathBuilder.build(Unknown Source) ~[?:1.7.0_80]
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source) ~[?:1.7.0_80]
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source) ~[?:1.7.0_80]
	at sun.security.validator.Validator.validate(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.Handshaker.processLoop(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.Handshaker.process_record(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.7.0_80]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394) ~[SSLConnectionSocketFactory.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353) ~[SSLConnectionSocketFactory.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) ~[DefaultHttpClientConnectionOperator.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[PoolingHttpClientConnectionManager.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[MainClientExec.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[MainClientExec.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[ProtocolExec.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[RetryExec.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[RedirectExec.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[InternalHttpClient.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[CloseableHttpClient.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[CloseableHttpClient.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	at kcauldron.updater.KVersionRetriever.check(KVersionRetriever.java:80) ~[KVersionRetriever.class:1.7.10-1448.UNOFFICIAL.55d1d75]
	... 2 more
[19:35:27] [Server thread/INFO]: There are 0/20 players online:

[19:35:29] [Server thread/INFO]: /authme reload|register playername password|changepassword playername password|unregister playername|version
[19:35:34] [Server thread/INFO]: /authme reload|register playername password|changepassword playername password|unregister playername|version
[19:35:47] [Server thread/INFO]: /authme reload|register playername password|changepassword playername password|unregister playername|version
[19:35:49] [Server thread/INFO]: CONSOLE: Stopping the server..
[19:35:49] [Server thread/INFO]: Stopping server
[19:35:49] [Server thread/INFO]: [AuthMe] Disabling AuthMe v${version}
[19:35:49] [Server thread/INFO]: Saving players
[19:35:49] [Server thread/INFO]: Saving worlds
[19:35:49] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[19:35:49] [Server thread/INFO]: Saving chunks for level 'DIM1'/The End
[19:35:49] [Server thread/INFO]: Saving chunks for level 'DIM-1'/Nether
[19:35:49] [Server thread/INFO]: Unloading dimension 0
[19:35:49] [Server thread/INFO]: Unloading dimension -1
[19:35:49] [Server thread/INFO]: Unloading dimension 1
[19:35:49] [Server thread/INFO]: Applying holder lookups
[19:35:49] [Server thread/INFO]: Holder lookups applied
And then Server is close.

**Comment by authme** [comment]
And you can see, I can't register the player (Client registration is not work too), and change passworld, and do any thing...

**Comment by Trojaner25** [comment]
Error occurred while enabling AuthMe v${version} (Is it up to date?)
java.lang.NoClassDefFoundError: net/milkbowl/vault/permission/Permission

You are missing vault

**Comment by authme** [comment]
But, I compiled by latest source code...

**Comment by sgdc3** [comment]
Try to download latest Vault version here: http://dev.bukkit.org/bukkit-plugins/vault/

**Comment by authme** [comment]
YES, the problem is missing Vault Plugin, but latest version is not supported 1.7.10, only supported 1.8+...

**Comment by Trojaner25** [comment]
Since this isn't really a bug or something:

#close request

**Comment by sgdc3** [comment]
Latest 1.7.10 Vault version: http://dev.bukkit.org/bukkit-plugins/vault/files/47-vault-1-4-1/

**Comment by authme** [comment]
YES, the problem only is lost Vault Plugin. To download it!
