### ISSUE TITLE
AuthMe v5.2-BETA2-b969 error

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#770]
[20:59:03] [Craft Scheduler Thread - 1504/WARN]: Exception in thread "Craft Scheduler Thread - 1504" 
[20:59:03] [Craft Scheduler Thread - 1504/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.2-BETA2-b969 generated an exception while executing task 24795
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at fr.xephi.authme.cache.limbo.LimboCache.deleteLimboPlayer(LimboCache.java:87)
	at fr.xephi.authme.process.quit.AsynchronousQuit.run(AsynchronousQuit.java:72)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more

**Comment by games647** [comment]
Already fixed since ee08087. Just update your build
