### ISSUE TITLE
"Activated" chat spam + random logouts.

### ISSUE THREAD

**Issue by Done84** [Xephi/AuthMeReloaded#795]
Hello. In one of my servers the chat is spammed with "ACTIVATED" every time a player logs in. Also players randomly have to /login again after they already did it for no reason.

Im using the latest build 1153
mc 1.8.9

also get this console error:
```
24.06 20:37:27 [Server] INFO default: d1One
24.06 20:36:13 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
24.06 20:36:13 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
24.06 20:36:13 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
24.06 20:36:13 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
24.06 20:36:13 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
24.06 20:36:13 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
24.06 20:36:13 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
24.06 20:36:13 [Server] INFO at fr.xephi.authme.process.SyncProcessManager$4.run(SyncProcessManager.java:69) ~[?:?]
24.06 20:36:13 [Server] INFO at fr.xephi.authme.process.login.ProcessSyncPlayerLogin.processPlayerLogin(ProcessSyncPlayerLogin.java:139) ~[?:?]
24.06 20:36:13 [Server] INFO at fr.xephi.authme.process.login.ProcessSyncPlayerLogin.sendBungeeMessage(ProcessSyncPlayerLogin.java:179) ~[?:?]
24.06 20:36:13 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1039) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
24.06 20:36:13 [Server] INFO at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:482) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
24.06 20:36:13 [Server] INFO org.bukkit.plugin.messaging.ChannelNotRegisteredException: Attempted to send a plugin message through the unregistered channel `BungeeCord'.
24.06 20:36:13 [Server] WARN Task #371 for AuthMe v5.2-SNAPSHOT-b1153 generated an exception
```

**Comment by sgdc3** [comment]
Activated spam: debug code of @games647 , blocked until the random logout issue isn't fixed

**Comment by games647** [comment]
>Also players randomly have to /login again after they already did it for no reason.

See ticket #419 

@sgdc3 What about the error?
>In one of my servers the chat is spammed with "ACTIVATED" every time a player logs in. 

It's seems the BungeeCord channel isn't registered by AuthMe

**Comment by sgdc3** [comment]
Maybe not a spigot server?

**Comment by games647** [comment]
@sgdc3 It seems to be one
>spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24

**Comment by sgdc3** [comment]
Maybe he activated bungeecord in the config after a reload.

**Comment by Done84** [comment]
Im not sure if its related or not but my guess is that it is, and its  major security issue.

 One of my players was able to lag himself really hard and spam commands until a "you are not activated" message shows without /Login, i don't have many details as hackers like to keep this stuff a secret but i do know it requires bungee...

**Comment by sgdc3** [comment]
every command is processed by authme, it's impossible to bypass the xmd protection

**Comment by ljacqu** [comment]
What needs to be done for this issue?

**Comment by ljacqu** [comment]
No answer
