### ISSUE TITLE
registration

### ISSUE THREAD

**Issue by TheDarkSkill** [Xephi/AuthMeReloaded#796]
```
[15:33:11] [Server thread/WARN]: [AuthMe] Task #87 for AuthMe v5.2-SNAPSHOT-b1153 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: No field with type int exists in class PacketPlayOutEntityDestroy.
	at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:347) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:327) ~[?:?]
	at fr.xephi.authme.listener.AuthMeInventoryPacketAdapter.sendInventoryPacket(AuthMeInventoryPacketAdapter.java:85) ~[?:?]
	at fr.xephi.authme.process.login.ProcessSyncPlayerLogin.restoreInventory(ProcessSyncPlayerLogin.java:74) ~[?:?]
	at fr.xephi.authme.process.login.ProcessSyncPlayerLogin.processPlayerLogin(ProcessSyncPlayerLogin.java:106) ~[?:?]
	at fr.xephi.authme.process.SyncProcessManager$4.run(SyncProcessManager.java:69) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[15:33:13] [Server thread/ERROR]: [AuthMe] Unhandled exception occured in onPacketSending(PacketEvent) for AuthMe
com.comphenix.protocol.reflect.FieldAccessException: No field with type int exists in class PacketPlayOutEntityDestroy.
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:218) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[ProtocolLib.jar:?]
	at fr.xephi.authme.listener.AuthMeInventoryPacketAdapter.onPacketSending(AuthMeInventoryPacketAdapter.java:65) ~[AuthMe-5.2-SNAPSHOT-spigot.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:638) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:614) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:312) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:278) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:417) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:84) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.handleScheduled(NettyChannelInjector.java:383) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.onMessageScheduled(NettyChannelInjector.java:351) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127) [ProtocolLib.jar:?]
	at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95) [ProtocolLib.jar:?]
	at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:194) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.NetworkManager.sendPacket(NetworkManager.java:143) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.PlayerConnection.sendPacket(PlayerConnection.java:1097) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.EntityPlayer.m(EntityPlayer.java:221) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1622) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.World.g(World.java:1597) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.WorldServer.l(WorldServer.java:655) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1398) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:632) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:804) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[15:33:13] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_10_R1.PacketPlayOutEntityDestroy@fb3b7[
    a={1648,1649}
  ]
```

**Comment by ljacqu** [comment]
CC: @games647
To confirm, this is on Spigot 1.10? And you have inventory protecting enabled, looks like?

**Comment by TheDarkSkill** [comment]
Yes 1.10, inventory protecting enabled

**Comment by TheDarkSkill** [comment]
After turning off the equipment to protect, was to write [15:59:04] [Server thread/WARN]: [AuthMe] Task #105 for AuthMe v5.2-SNAPSHOT-b1153 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_66]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_66]
	at com.comphenix.protocol.wrappers.EnumWrappers.getEnum(EnumWrappers.java:344) ~[?:?]
	at com.comphenix.protocol.wrappers.EnumWrappers.initialize(EnumWrappers.java:300) ~[?:?]
	at com.comphenix.protocol.wrappers.EnumWrappers.getPlayerInfoActionClass(EnumWrappers.java:392) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer.getPlayerInfoAction(PacketContainer.java:772) ~[?:?]
	at fr.xephi.authme.listener.AuthMeTablistPacketAdapter.sendTablist(AuthMeTablistPacketAdapter.java:88) ~[?:?]
	at fr.xephi.authme.process.login.ProcessSyncPlayerLogin.processPlayerLogin(ProcessSyncPlayerLogin.java:110) ~[?:?]
	at fr.xephi.authme.process.SyncProcessManager$4.run(SyncProcessManager.java:69) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]

**Comment by games647** [comment]
Try to update your ProtocolLib version

**Comment by sgdc3** [comment]
@games647 maybe we should add a protocollib version check

**Comment by games647** [comment]
@sgdc3 I don't think it's necessary. Updates should be always applied. ProtocolLib already has an auto updater. Moreover I think this can be very complicated based on the experience I made with ScoreboardStats. We would have to check if it works manually and if a user doesn't has the most recent authme version, the user won't see our new "please update to X"-message too.

**Comment by games647** [comment]
@TheDarkSkill Do you fixed it?

**Comment by TheDarkSkill** [comment]
@games647 Yes

**Comment by games647** [comment]
@TheDarkSkill Thanks. Then I'm closing this.
