### ISSUE TITLE
Add blindness effect synchronously

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#828]
AsynchronousUnregister is trying to add blindness effect in a non-synchronous thread

```java
Caused by: java.lang.IllegalStateException: Asynchronous effect add!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
	at net.minecraft.server.v1_8_R3.EntityLiving.addEffect(EntityLiving.java:582)
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:303)
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:293)
	at fr.xephi.authme.process.unregister.AsynchronousUnregister.unregister(AsynchronousUnregister.java:85)
```

**Comment by ljacqu** [comment]
Thanks @games647, only noticed your commit now. I checked it just now, so closing.
