### ISSUE TITLE
Exception.

### ISSUE THREAD

**Issue by molor** [Xephi/AuthMeReloaded#856]
I think that i found a bug.

```
[13:42:13 INFO]: player logged in with entity id 1790 at ([level_name]1331, 75, 1239)
[13:42:14 INFO]: [AuthMe] player logged in!
[13:42:15 WARN]: [AuthMe] Task #930 for AuthMe v5.2-SNAPSHOT-b1214 generated anexception
java.lang.NullPointerException
        at fr.xephi.authme.util.TeleportationService.teleportOnLogin(TeleportationService.java:112) ~[?:?]
        at fr.xephi.authme.process.login.ProcessSyncPlayerLogin.processPlayerLogin(ProcessSyncPlayerLogin.java:100) ~[?:?]
        at fr.xephi.authme.process.SyncProcessManager$4.run(SyncProcessManager.java:69) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[13:42:41 INFO]: player issued server command: /login
[13:42:41 INFO]: [AuthMe] player logged in!
[13:42:41 WARN]: [AuthMe] Task #997 for AuthMe v5.2-SNAPSHOT-b1214 generated anexception
java.lang.NullPointerException
        at fr.xephi.authme.util.TeleportationService.teleportOnLogin(TeleportationService.java:112) ~[?:?]
        at fr.xephi.authme.process.login.ProcessSyncPlayerLogin.processPlayerLogin(ProcessSyncPlayerLogin.java:100) ~[?:?]
        at fr.xephi.authme.process.SyncProcessManager$4.run(SyncProcessManager.java:69) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[13:42:53 INFO]: player issued server command: /login
[13:42:56 INFO]: player issued server command: /gamemode spectator
[13:42:59 INFO]: player issued server command: /gamemode creative
[13:43:02 INFO]: <player> i can't move
```

**Comment by ljacqu** [comment]
@molor Could you share your config.yml please? Is there anything special about this player?

**Comment by molor** [comment]
@ljacqu, about player - nothing, just a builder on server..
config.yml: http://pastebin.com/KVHz0yES

**Comment by ljacqu** [comment]
@molor Thanks for the config file. I think the issue when we persist some player data to a file, we might be missing some location info. Did you perhaps rename or delete a world recently?

You should no longer experience this bug with build nr. 1218 or above. http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by molor** [comment]
> Did you perhaps rename or delete a world recently?

no. Thanks for fix!

**Comment by ljacqu** [comment]
No problem, thanks for reporting it. Do you have a world whose name has something other than [a-z] lowercase characters?

**Comment by molor** [comment]
> Do you have a world whose name has something other than [a-z] lowercase characters?

Server contains only these three worlds: level_name, level_name_nether & level_name_the_end.

**Comment by ljacqu** [comment]
OK, thank you for all of the information :smile:

**Comment by sgdc3** [comment]
@ljacqu Can we close that? :)

**Comment by ljacqu** [comment]
Yes, we can
