### ISSUE TITLE
Legacy build 1254 no messages on login/no move after login on MC 1.7.2

### ISSUE THREAD

**Issue by hsombini** [Xephi/AuthMeReloaded#885]
Hello,

Legay build 1254 should be compatible with 1.7.2?

I had some issues trying to run it!

1. On server join, no message is sent to the player, asking to /register or /login, but the player can perform the command /register or /login normaly, the welcome message is displayed after the player perform /login

2. When a player login, he can't move, I've tryed to relog several times.

Error on console on player login
`[06:26:47] [Craft Scheduler Thread - 6/WARN]: Exception in thread "Craft Scheduler Thread - 6" 
[06:26:47] [Craft Scheduler Thread - 6/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.2-SNAPSHOT-b1254 generated an exception while executing task 27
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.OfflinePlayer.getUniqueId()Ljava/util/UUID;
	at fr.xephi.authme.util.Utils.getUUIDorName(Utils.java:28)
	at fr.xephi.authme.cache.backup.PlayerDataStorage.removeData(PlayerDataStorage.java:113)
	at fr.xephi.authme.cache.limbo.LimboCache.deletePlayerData(LimboCache.java:98)
	at fr.xephi.authme.process.join.AsynchronousJoin.processJoin(AsynchronousJoin.java:149)
	at fr.xephi.authme.process.Management$5.run(Management.java:86)
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more`

Thanks!

**Comment by sgdc3** [comment]
@hsombini Fixed, wait 2 minutes and download latest build from jenkins ;)

**Comment by sgdc3** [comment]
@hsombini does it work?

**Comment by Twonox** [comment]
I have the same problem but only after /reload.
When I relog I can move (but with a speed effect), and after 3 seconds I can't move again. I must do /speed 1 to can walk again.
I don't receive error message and I use the latest build with `removeSpeed: true`

**Comment by hsombini** [comment]
@Twonox do not /reload your production server, just don't

@sgdc3 it's working now, i'll close this issue
