### ISSUE TITLE
Hooking into bungeecord on /authme reload fails

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#889]
If your config.yml has `bungeecord: false` and you change it to `true` before doing an `/authme reload`, the plugin will start generating exceptions:

```
[09:36:58 WARN]: [AuthMe] Task #34 for AuthMe v5.2-SNAPSHOT-bCUSTOM generated an exception
org.bukkit.plugin.messaging.ChannelNotRegisteredException: Attempted to send a plugin message through the unregistered channel `BungeeCord'.
	at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:482) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1039) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at fr.xephi.authme.service.BungeeService.sendBungeeMessage(BungeeService.java:55) ~[?:?]
	at fr.xephi.authme.process.register.ProcessSyncPasswordRegister.processPasswordRegister(ProcessSyncPasswordRegister.java:95) ~[?:?]
	at fr.xephi.authme.process.SyncProcessManager$2.run(SyncProcessManager.java:51) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:744) [?:1.7.0_51]
```

This is nothing major as it only happens on in-game reload.

**Comment by sgdc3** [comment]
@ljacqu We should merge the listener with the service maybe, @ljacqu

**Comment by sgdc3** [comment]
We can't reload the bungee hook because the channel registration is done in the onEnable method...

**Comment by ljacqu** [comment]
So basically the following code needs moving
```java
    /**
     * Set up the BungeeCord hook.
     */
    private void setupBungeeCordHook() {
        if (settings.getProperty(HooksSettings.BUNGEECORD)) {
            Messenger messenger = Bukkit.getMessenger();
            messenger.registerOutgoingPluginChannel(this, "BungeeCord");
            messenger.registerIncomingPluginChannel(this, "BungeeCord", injector.getSingleton(BungeeCordMessage.class));
        }
}
```

from the AuthMe class into `BungeeService` or `BungeeCordMessage` and `Reloadable` has to be implemented.

**Comment by sgdc3** [comment]
What about `injector.getSingleton(BungeeCordMessage.class` can i move it to the service?

**Comment by ljacqu** [comment]
I would suggest to replace it as an `@Inject` field instead:
```java
@Inject
private BungeeCordMessage bungeeCordMessage;
```
That makes it just a normal dependency of the service class.

**Comment by sgdc3** [comment]
Where should i register the bungeeCordMessage class?

**Comment by ljacqu** [comment]
Probably inside the reload command with a boolean field that keeps track whether the channel has been already registered, i.e. something like:

```java
@PostConstruct
@Override
public void reload() {
  if (!isChannelRegistered && settings.getProperty(HooksSettings.BUNGEECORD)) {
     // register channel
     Messenger messenger = Bukkit.getMessenger(); // etc.
     isChannelRegistered = true;
  }
}

**Comment by sgdc3** [comment]
Look at my commit, i'm sure i'm missing the Injector initialization

**Comment by ljacqu** [comment]
verified in joint session with @sgdc3
