### ISSUE TITLE
Error on Email recovery password

### ISSUE THREAD

**Issue by jeremy100** [Xephi/AuthMeReloaded#956]
Hi, while trying to retrieve the password the server gives an error and does not send it. But by creating a new user if the Email sent successfully.

I enabled access GMAIL unsafe applications and does not work as shown in this guide:
http://stackoverflow.com/questions/26393906/error-sending-email-with-gmail/27815241#27815241
**Build #1385**
Error on Authme.log:
`[09-27 22:39:08]: [WARN] Failed to send a mail to [xxx@gmail.com]: [EmailException]: Sending the email to the following server failed : smtp.1and1.es:587
[09-27 22:39:08]: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.1and1.es:587
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1421)
	at org.apache.commons.mail.Email.send(Email.java:1448)
	at fr.xephi.authme.mail.SendMailSSL.sendEmail(SendMailSSL.java:158)
	at fr.xephi.authme.mail.SendMailSSL.sendRecoveryCode(SendMailSSL.java:111)
	at fr.xephi.authme.command.executable.email.RecoverEmailCommand.createAndSendRecoveryCode(RecoverEmailCommand.java:87)
	at fr.xephi.authme.command.executable.email.RecoverEmailCommand.runCommand(RecoverEmailCommand.java:75)
	at fr.xephi.authme.command.PlayerCommand.executeCommand(PlayerCommand.java:16)
	at fr.xephi.authme.command.CommandHandler.executeCommand(CommandHandler.java:112)
	at fr.xephi.authme.command.CommandHandler.handleCommandResult(CommandHandler.java:71)
	at fr.xephi.authme.command.CommandHandler.processCommand(CommandHandler.java:64)
	at fr.xephi.authme.AuthMe.onCommand(AuthMe.java:400)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	javax.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/alternative; 
	boundary="----=_Part_0_1572570306.1475008738284"
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1244)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1411)
	... 26 more
Caused by: javax.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/alternative; 
	boundary="----=_Part_0_1572570306.1475008738284"
	at javax.activation.ObjectDataContentHandler.writeTo(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1608)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1849)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1196)
	... 29 more`

**Comment by ljacqu** [comment]
Thanks for the report. This should be fixed with build n. 1386 or above, please let us know if this can be closed. http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by jeremy100** [comment]
Works fine! thanks :) @ljacq

**Comment by ljacqu** [comment]
Thanks!
