### ISSUE TITLE
Email Recovery

### ISSUE THREAD

**Issue by AmazedMender16** [Xephi/AuthMeReloaded#984]
Email recovery doesnt seem to work

[10-17 16:10:28]: [INFO] SQLite driver loaded
[10-17 16:10:28]: [INFO] SQLite Setup finished
[10-17 16:10:28]: [INFO] Hooked into PermissionsEx!
[10-17 16:10:28]: [INFO] [LICENSE] This product uses data from the GeoLite API created by MaxMind, available at http://www.maxmind.com
[10-17 16:10:28]: [INFO] Hooked successfully into Essentials
[10-17 16:10:28]: [INFO] Hooked successfully into Multiverse-Core
[10-17 16:10:28]: [INFO] Development builds are available on our jenkins, thanks to f14stelt.
[10-17 16:10:28]: [INFO] Do you want a good game server? Look at our sponsor GameHosting.it leader in Italy as Game Server Provider!
[10-17 16:10:28]: [INFO] AuthMe 5.2-SNAPSHOT build n.1416 correctly enabled!
[10-17 16:11:27]: [WARN] Failed to send a mail to [****@hotmail.nl]: [EmailException]: Sending the email to the following server failed : sbwebnode.nl:587
[10-17 16:11:27]: org.apache.commons.mail.EmailException: Sending the email to the following server failed : sbwebnode.nl:587
    at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1421)
    at org.apache.commons.mail.Email.send(Email.java:1448)
    at fr.xephi.authme.mail.SendMailSSL.sendEmail(SendMailSSL.java:158)
    at fr.xephi.authme.mail.SendMailSSL.sendRecoveryCode(SendMailSSL.java:110)
    at fr.xephi.authme.command.executable.email.RecoverEmailCommand.createAndSendRecoveryCode(RecoverEmailCommand.java:87)
    at fr.xephi.authme.command.executable.email.RecoverEmailCommand.runCommand(RecoverEmailCommand.java:75)
    at fr.xephi.authme.command.PlayerCommand.executeCommand(PlayerCommand.java:16)
    at fr.xephi.authme.command.CommandHandler.executeCommand(CommandHandler.java:112)
    at fr.xephi.authme.command.CommandHandler.handleCommandResult(CommandHandler.java:71)
    at fr.xephi.authme.command.CommandHandler.processCommand(CommandHandler.java:64)
    at fr.xephi.authme.AuthMe.onCommand(AuthMe.java:391)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647)
    at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358)
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193)
    at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
    at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
    at java.lang.Thread.run(Unknown Source)
Caused by: javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
    javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1999)
    at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:709)
    at javax.mail.Service.connect(Service.java:386)
    at javax.mail.Service.connect(Service.java:245)
    at javax.mail.Service.connect(Service.java:194)
    at javax.mail.Transport.send0(Transport.java:253)
    at javax.mail.Transport.send(Transport.java:124)
    at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1411)
    ... 26 more
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.ssl.Alerts.getSSLException(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
    at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
    at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
    at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
    at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
    at sun.security.ssl.Handshaker.processLoop(Unknown Source)
    at sun.security.ssl.Handshaker.process_record(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
    at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:543)
    at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:480)
    at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1994)
    ... 33 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
    at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
    at sun.security.validator.Validator.validate(Unknown Source)
    at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
    at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
    at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
    ... 44 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
    at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
    at java.security.cert.CertPathBuilder.build(Unknown Source)
    ... 50 more

[10-17 16:11:37]: [INFO] AuthMe 5.2-SNAPSHOT-b1416 disabled!

**Comment by sgdc3** [comment]
Probably email server connection misconfiguration, please write there if you need more help.
