### ISSUE TITLE
Error with email system

### ISSUE THREAD

**Issue by arturek1666** [Xephi/AuthMeReloaded#999]
Using PaperSpigot 1.10.2
Plugins:  CoreProtect, AsyncWorldEditInjector, CustomHelpMessage, EasyElevators, DeathLogPlus, HealthBar, ItemSearch, XRayDetector, iConomy_Recreation, ClearLag, PluginManager, ChatControl, AdvancedBan, WorldBorder, ProtocolLib, Multiverse-Core, SkinsRestorer, AsyncWorldEdit, VoxelSniper, TradePlus, EditableSign, SignStatus, Tablist, Vault, StaffPlus, ItemRestrict, LuckPerms, WorldEdit, Essentials, HolographicDisplays, Marriage, WorldGuard, TreasureChest, Citizens, ChopTree3, EssentialsProtect, EssentialsChat, EssentialsAntiBuild, RandomTeleport, GlobalChestShop, ProtectionStones, EssentialsSpawn, WorldGuardExtraFlags, ChestShop, AuthMe

[11-05 19:56:46]: [INFO] AuthMe 5.2-SNAPSHOT build n.1384 correctly enabled!
[11-05 19:57:12]: [WARN] Failed to send a mail to [xxxxxxxxxxxx@gmail.com]: [EmailException]: Sending the email to the following server failed : smtp.gmail.com:465
[11-05 19:57:12]: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1421)
	at org.apache.commons.mail.Email.send(Email.java:1448)
	at fr.xephi.authme.mail.SendMailSSL.sendEmail(SendMailSSL.java:158)
	at fr.xephi.authme.mail.SendMailSSL.sendRecoveryCode(SendMailSSL.java:111)
	at fr.xephi.authme.command.executable.email.RecoverEmailCommand.createAndSendRecoveryCode(RecoverEmailCommand.java:87)
	at fr.xephi.authme.command.executable.email.RecoverEmailCommand.runCommand(RecoverEmailCommand.java:75)
	at fr.xephi.authme.command.PlayerCommand.executeCommand(PlayerCommand.java:16)
	at fr.xephi.authme.command.CommandHandler.executeCommand(CommandHandler.java:112)
	at fr.xephi.authme.command.CommandHandler.handleCommandResult(CommandHandler.java:71)
	at fr.xephi.authme.command.CommandHandler.processCommand(CommandHandler.java:64)
	at fr.xephi.authme.AuthMe.onCommand(AuthMe.java:400)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:672)
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1396)
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1201)
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:808)
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740)
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	javax.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/alternative; 
	boundary="----=_Part_0_1284442988.1478375831049"
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1244)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1411)
	... 26 more
Caused by: javax.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/alternative; 
	boundary="----=_Part_0_1284442988.1478375831049"
	at javax.activation.ObjectDataContentHandler.writeTo(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1608)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1849)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1196)
	... 29 more

**Comment by ljacqu** [comment]
Did you edit email.html or the other .html file? If so please delete them and try with the default one.

**Comment by arturek1666** [comment]
I did try it's the same issue.

**Comment by arturek1666** [comment]
Also checked Spigot, and paperspigot just to test it still nothing

**Comment by ljacqu** [comment]
Hi @arturek1666, sorry for the long wait. Could you please try with build n. 1452 or above? 
http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by arturek1666** [comment]
Yea it works :) thanks for help

**Comment by ljacqu** [comment]
Thanks for the feedback!
